### ISSUE TITLE
Opnsense’s Update of today

### ISSUE THREAD

**Issue by boistordu** [FingerlessGlov3s/OPNsensePIAWireguard#10]
Hi,

I think I have a problem since the update of today. 
Since I m not quite sure about all the concepts of gateway simple and extended of opnsens, I want to check up with you...
Could you look into it ? 
There has been an update of wireguard today with the other firmware update and the traffic is not redirected to my wireguard gateway and there is actually no more gateway from wireguard even if the service is still active and there is still a connectivity apparently

**Comment by FingerlessGlov3s** [comment]
Hi,

Have you updated your script to the latest version, I added a change to the script to fix an issue I found after upgrading to 21.1.4. Not to say there's isn't another edge case brought in by the update. So far I've tested it on 3 OPNsense installs, without any issues.

I'm also confused on what you mean by "concepts of gateway simple and extended". If you could elaborate that would be great. 😁

Could you take a screenshot of your gateway status in OPNsense, and then the routes status in OPNsesne. Example below.

Gateways
![image](https://user-images.githubusercontent.com/3495647/113106016-2a274400-91fa-11eb-80db-c2d6a9d63a2d.png)

Routes (your interface maybe wg0 not wg1)
![image](https://user-images.githubusercontent.com/3495647/113106045-357a6f80-91fa-11eb-81c0-73c553a75b26.png)

FingerlessGloves

**Comment by boistordu** [comment]
Sorry didn't update the script will do today then and see what happens. 
Should I delete anything before to redo all the process ?

**Comment by FingerlessGlov3s** [comment]
Simply, replace the PIAWireguard.py with the new version, make sure you put your variables back in of course, no other changes required.

**Comment by boistordu** [comment]
Okey redone the whole protocol. 
We should not forget to add a step about reactivate the gateway or at least check it's activated in the section gateway. 
Mine was deactivate after redone everything.


About the concept I m still not familiar is:
- Far gateway 
- The one just before far gateway(mine is in another language so let's translate by ), upstream gateway ?
- Dynamic gateway policy win interfaces where you can check "this interface does not require an intermediate system to act as a gateway"

I didn't find clear explanation in the doc about all that.

**Comment by FingerlessGlov3s** [comment]
Glad you got it working now. I'm not sure why your gateway disabled itself, first I've seen this behaviour. I've added extra step in the guide to make sure disabled is unchecked. https://github.com/FingerlessGlov3s/OPNsensePIAWireguard/commit/fa4bfcfafd33ed528738d0e693af3cf6992c40fa

Far Gateway is used when the gateway for that network/interface sits outside of the interface's network range. Allows you to define a gateway outside of your network and enable the routing for  it.

If I remember correctly upstream gateway is about the default 0.0.0.0 route of OPNsense.

Dynamic gateway policy I've never used myself, so you'll have to google that one.
