### ISSUE TITLE
Use of the wireguard interface for another vpn connection

### ISSUE THREAD

**Issue by boistordu** [FingerlessGlov3s/OPNsensePIAWireguard#12]
Hi,

I have a small problem and since this is new for me I'm not quite sure where the problem could be. I have several hypothesis. 

I wanted to use the wireguard setup as a gateway for another OpenVPN to another organization (not big vpn provider but just an small foundation) because I don't want them to record my real IP address. 
The connection was successful but then the wireguard gateway did go down nearly in an instant and so the OpenVPN of course. The OpenVPN didn't go back up but the wireguard gateway did thanks to our Cron job and the monitoring of course. 

What could it be ? 

Would it be a protection of PIA ? 
Would it be a problem in the configuration of OpenVPN like the don t pull route unchecked ?  

If you have any ideas, please share.
Thanks

**Comment by boistordu** [comment]
It was the don't pull route that was unchecked actually.
Sorry for the disturbance

**Comment by FingerlessGlov3s** [comment]
I was just about to reply, saying its probably routing issue with the pull routes 🤭

**Comment by boistordu** [comment]
I wanted to add something since I've upgrade to fedora 34 server this specific server and it seems that there is a incompatibility of some sort now. 
Unless the frankfurt wireguard is overloaded for the moment but I do'nt think so since everything is working fine with one tunnel activated.


ping is working strangely 
nslookup too
but I can't reach the vm from outside and some tcp transaction from apt-get are not reaching either. 
Where actually if I move the tunnel link on another openvpn link, it's totally fine.

**Comment by FingerlessGlov3s** [comment]
Have you double checked the settings you've input in to OPNsense match what they should be in the README.md?

Other than that, probably going to need some information around firewall rules, NAT, WireGuard and Maximum MSS values.

**Comment by boistordu** [comment]
yeah I didn't change anything, it's still the same VM which was working before... But actually I'm trying with another vpn , same kind but from another organization but through the same wg0 link and it seems to work.... So maybe this has nothing to do with my setup and maybe more with BGP routes between PIA wireguard and the first vpn organization.
