### ISSUE TITLE
wireguardserver generateToken request failed non 200 status code - Trying to get PIA token

### ISSUE THREAD

**Issue by MadTomT** [FingerlessGlov3s/OPNsensePIAWireguard#13]
Hi,

Just trying this and I've added my PIA username, password, regionID and opensense Key & Secret to PIAWireguard.py

I've restarted configd
When I /conf/PIAWireguard.py debug  I get:

WGInstanceUUID: XXXXXXXXXX
WGPeerUUID: XXXXXXXXXXXXXX
WGInstance: XXXXXXXXXXX
WGPeer: XXXXXXXXXXXXXX
metaServer
[{'ip': '143.244.36.58', 'cn': 'southampton405'}]
wgServer
[{'ip': '143.244.36.96', 'cn': 'southampton405'}]
wireguardserver generateToken request failed non 200 status code - Trying to get PIA token

All the XXXXXXXX entries have real values in them, but I've obscured them as I wasn't sure if they were private..

How do I resolve this ?
I've checked my PIA credentials are correct.

Thanks

**Comment by notarobot63** [comment]
Hello,

Same here on OPNSense 21.1.4 
I'm wondering if this is a script issue or an API issue ?

**Comment by MadTomT** [comment]
Where you using a UK region?
If so, what did you change to ?
Thanks

**Comment by notarobot63** [comment]
I was on nl_amsterdam and tried montenegro and sweden and it was ok.

**Comment by MadTomT** [comment]
Thanks, I'll try a couple of different servers :)

**Comment by FingerlessGlov3s** [comment]
Hey, Where have you lot got with the testing?

Sorry for the delay, was putting in network cables.

**Comment by FingerlessGlov3s** [comment]
Just doing some testing, I got the issue with london402 and london405, but london434 and london403 was ok. Shall see testing, and sees what's going on, its getting bad gateway. Looks to be PIA side but shall investigate.

**Comment by FingerlessGlov3s** [comment]
Update: This issue is PIA and they have been notified.

**Comment by notarobot63** [comment]
That seemed to be only on geoblocked servers ?

**Comment by FingerlessGlov3s** [comment]
Issue should now be fixed on all regions now. Closing issue, please reopen if issue is still happening.
