### ISSUE TITLE
Port Forwarding issue

### ISSUE THREAD

**Issue by notarobot63** [FingerlessGlov3s/OPNsensePIAWireguard#14]
Hello,
So your script is working perfectly, but I have a problem with Port Forwarding part. 
I've enabled piaPortForward in the script and the alias is being created.
I've setup a Nat Rule to allow packets incoming on VPN address on PIA_PORT to go to my host on PIA_Port.

The port still shows as closed. 
I think I may have missed something ?

**Comment by FingerlessGlov3s** [comment]
How are you checking if the port is closed? Have you tried pointing it to something simple like a Web Server, then checking the PIA IP and port from a mobile phone?

Oh Linux system you can start a simple web server by doing `python -m SimpleHTTPServer 12345` `12345` being the PIA port you are given.

Just double checked my PIA port forward, still reporting as open in Transmission
![image](https://user-images.githubusercontent.com/3495647/115149912-184cfa00-a05e-11eb-94ef-2afdaef4f19f.png)

**Comment by notarobot63** [comment]
I'm checking it with Transmission which keep saying the port is closed.

**Comment by FingerlessGlov3s** [comment]
Have you double checked Transmissions is 100% using the PIA tunnel?

You can use this site here to check what IP a torrent client is using https://ipleak.net/

**Comment by notarobot63** [comment]
Just tested with your link Transmission is indeed using the tunnel. I have a killswitch in case the tunnel is down anyway.
I can't figure out what's wrong...

**Comment by FingerlessGlov3s** [comment]
are there's any major differences between my NAT rule and yours?
![image](https://user-images.githubusercontent.com/3495647/115150302-a970a080-a05f-11eb-9612-3e538d06a93f.png)

I then have this script which then updates the port on transmissions automatically, for when the PIA server changes etc.
https://gist.github.com/FingerlessGlov3s/d7047953a0b99832210591653ebae7b0

**Comment by notarobot63** [comment]
That is pretty much the same rule I use with one exception: I'm using the VPN Interface which is assigned to Wireguard.
![image](https://user-images.githubusercontent.com/51323017/115150542-23595780-a069-11eb-94bd-989e4beb4df4.png)

**Comment by FingerlessGlov3s** [comment]
This should all be working then.. unless Transmissions is just reporting wrong.

Have you checked the port with a port scanner https://www.whatismyip.com/port-scanner/ ?

**Comment by notarobot63** [comment]
Yes I tried with an online service and it also report it closed.
I'm trying to check my firewall rules in case this is it

**Comment by FingerlessGlov3s** [comment]
When you create the port forward, the default setting of `Filter rule association` is set too `Add associated filter rule`, which will get the required rule on the VPN interface to allow the traffic to pass.

**Comment by notarobot63** [comment]
Here is what I've got: 
![image](https://user-images.githubusercontent.com/51323017/115151159-f9556480-a06b-11eb-9d61-6c1f00174428.png)
Guess we have a problem here....

**Comment by FingerlessGlov3s** [comment]
Indeed, that would be the issue, simplest way is to recreate the rule, leaving the `Filter rule association` default selection.

**Comment by notarobot63** [comment]
I recreated the rules with correct option and I have a new rule in my VPN interface, but this damn port is still showing as closed.

**Comment by FingerlessGlov3s** [comment]
Change server and see if that makes a difference `/conf/PIAWireguard.py changeserver`. Encase the port is reported closed for too long and then PIA remove it, not sure if they monitor them or not.

**Comment by notarobot63** [comment]
Weirdly, evrywhere it shows port 51815 but in https://opnsense/wg0_port.txt there's another one ?

**Comment by notarobot63** [comment]
Here is what I have when I change server:
![image](https://user-images.githubusercontent.com/51323017/115153713-ab465e00-a077-11eb-8bfe-eebab270a6c6.png)
The alias in OPNsense has been changed to the correct one though (here 35833) but in Wireguard --> Local it's the wrong one.
Changing it lead to no improvements whatsoever.

**Comment by FingerlessGlov3s** [comment]
WireGuard Local port, isn't Whats used for port forwarding, its for the WireGuard traffic as a whole.

`FIREWALL: SETTINGS: ADVANCED` what settings for NAT do you have?
![image](https://user-images.githubusercontent.com/3495647/115153931-3cb1d200-a070-11eb-88fe-7940f8729796.png)

**Comment by notarobot63** [comment]
Exact same as you

**Comment by FingerlessGlov3s** [comment]
Did you change the local instance of wireguard port back?

Next would be to enable logging for the NAT rule and see if you can see the traffic coming in to OPNsense.

**Comment by notarobot63** [comment]
I'll call it a night for now, I'll check in the morning tomorrow.
Thanks for the help !

**Comment by FingerlessGlov3s** [comment]
Might be worth going deeper with the checking for traffic using tcpdump command in OPNsense CLI. Then you can see the traffic on the interface even if OPNsense isn't logging it. Then if you can see it on wg0, then you can go on to check the lan interface transmission is on, to see if its gotten forwarded.

`tcpdump -n -i wg0 port 12345` changing `12345` for the port forward port

**Comment by notarobot63** [comment]
OK so I the logs I only see traffic going out of the LAN interface (nothing blocked) and with tcpdump no traffic at all on the port on wg0.

**Comment by FingerlessGlov3s** [comment]
So if you use your phone or port scanner website, you can see the traffic enter wg0, then come out the LAN?

**Comment by notarobot63** [comment]
Yes exactly

**Comment by FingerlessGlov3s** [comment]
So the port forward is working as expected. Is the machine running transmissions got any firewalls or anything for inbound traffic?

**Comment by notarobot63** [comment]
I'm dumb in tcpdump I see traffic only between tunnel address and Endpoint address ! There is nothing coming from elsewhere...

**Comment by FingerlessGlov3s** [comment]
If you got Teamviewer, email me, and we'll go from there, might be easier if I can see the issue hands on, if that's ok with you. I've got some free time in 30 minutes.

me@fingerlessgloves.me

**Comment by notarobot63** [comment]
That's really nice but I'd rather not. I will look further tomorrow.

**Comment by FingerlessGlov3s** [comment]
Cool no worries,

Oh that's odd, its not that old 🤣, which RSS reader?

**Comment by notarobot63** [comment]
I think I stumble upon your article on scrutiny and I add it to my Freshrss instance

**Comment by notarobot63** [comment]
@FingerlessGlov3s If that's possible, can you senda screenshot of your Wireguard settings in OPNsense UI ? Endpoints and local should be enough
Thanks a lot !

**Comment by FingerlessGlov3s** [comment]
Sure see below

Instance
![image](https://user-images.githubusercontent.com/3495647/115395251-94208100-a1db-11eb-9fbf-84b8cacd2d3b.png)

Peer
![image](https://user-images.githubusercontent.com/3495647/115395309-a39fca00-a1db-11eb-8d23-792b284389fc.png)

Might be worth removing it all and starting again, if you think you've changed something you shouldn't have.

**Comment by notarobot63** [comment]
Ok and is "Listen port" the same or different than the port you want to forward ?

Envoyé depuis ProtonMail mobile

-------- Message d'origine --------

**Comment by FingerlessGlov3s** [comment]
Listen port is not related to the port forwarded, that's for the tunnel traffic itself. My PIA forwarded port is 45046

**Comment by notarobot63** [comment]
ok so everything is fine on this part for me at least that is something that I'm sure of.

**Comment by FingerlessGlov3s** [comment]
The script takes care of creating and maintaining the WireGuard instances, PIA peer and PIAPort Alias. You don't need to touch these parts,

Then you create your outbound NAT rules as required, then to do port forwarding you enable the port forwarding variable which will create and populate the PIAPort Alias. Then you use it in a Port Forwarding rule.

I'm not sure why its not working, I've setup this on a few OPNsense instances myself with no problems and I know others have too.

**Comment by FingerlessGlov3s** [comment]
Have you tried using a different region? Try London, I use this region and its been working fine for months.

**Comment by notarobot63** [comment]
Yes the script in itself is working fine. I suspect a conflict with prexisting NAT rules or Firewall rules. 
I'm currently trying a different set of rules. That'll teach me to document every rule I create...

**Comment by FingerlessGlov3s** [comment]
Yeah documentation is always good, or leave very descriptive descriptions :-)

**Comment by notarobot63** [comment]
I tried London, is this normal ?
![image](https://user-images.githubusercontent.com/51323017/115398567-938de780-a1e7-11eb-9d56-5b0b5f531a14.png)

**Comment by FingerlessGlov3s** [comment]
Indeed, every time to change server, PIA will give you a new random port number.

**Comment by notarobot63** [comment]
OK but how come opnsense.local/wg0_port.txt never change ? From what I understand it should now be 43864 but it still shows 55120.

**Comment by FingerlessGlov3s** [comment]
When it changes server or detects it doesn't have a port yet, it'll request a new port from PIA, it'll then save the port number in to the txt file.

See here
https://github.com/FingerlessGlov3s/OPNsensePIAWireguard/blob/fa4bfcfafd33ed528738d0e693af3cf6992c40fa/PIAWireguard.py#L576

I'm not sure why your txt didn't update, as it should of done. Make sure your browser didn't cache, either use incognito or use Shift + F5, to refresh clearing the cache.

**Comment by notarobot63** [comment]
ok that was a browser cache issue sorry. 
Anyway I'll stop bothering you as from what I see the problem is clearly not coming from you script whis is working fine.
I'll try to sort all my rules out.

**Comment by FingerlessGlov3s** [comment]
I'll leave this issue open, and when you find out what it is, you can reply what it was and close it :-)

**Comment by FingerlessGlov3s** [comment]
Not heard anything in a good few months now, shall close.
