### ISSUE TITLE
How to change PIA server ?

### ISSUE THREAD

**Issue by MadTomT** [FingerlessGlov3s/OPNsensePIAWireguard#15]
Hi, 

Is there a guide on how to change the PIA server used ?
or is it as simple as editing the endpoint IP Address in VPN -> Wireguard ?

Thanks

**Comment by FingerlessGlov3s** [comment]
Unfortunately its not as simple as setting the PIA Server endpoint address, since authentication with the WireGuard Public keys in the payload is required, hence why this script exists.

What's the requirement to connect to a singular PIA server? Isn't setting the region alone enough?

Please note, setting it to a single PIA server may cause you more issues in the long run, as and when PIA decommission servers or rotate their IPs.

**Comment by MadTomT** [comment]
Hi. My issue is very poor intermittent access via the VPN.
Some sites work, others don't. Sometimes its fast, other times very slow.
I wanted to try another server to see how that was.  

I was using openVPN on pfSense and the VPN seemed to be OK. This is the first time I've used wireguard and was hoping to swap servers to see if that helped.

Thanks

**Comment by FingerlessGlov3s** [comment]
If you run `/conf/PIAWireguard.py debug changeserver` in the console, you'll see the script change to the next best PIA server (at that time of running the script) and will print the server name in the debug information.

When setting up WireGuard tunnels (like this script does), setting up the Maximum MSS rule in `Firewall: Settings: Normalization` is very important to make sure TCP performance (Web Browsing) is as good as it should be.

If you want any parts of the setup validated, just screenshot the settings you've put, and I shall be able to see if everything is looking as it should.

**Comment by MadTomT** [comment]
Thanks I will try this tomorrow.
Is wireguard more intensive than openVPN ? I'm currently running on a box with a J1900 CPU and I wonder if that is causing the issue ! Thanks

**Comment by FingerlessGlov3s** [comment]
If you install the kmod version of WireGuard on OPNsense, people are getting more performance than OpenVPN, on low end CPUs. I've seen people go from 40-50mbps to 250mbps

How to
https://fingerlessgloves.me/2021/04/12/two-weeks-with-wireguard-kmod-opnsense/

**Comment by MadTomT** [comment]
Thanks for this. If I install then kmod and have issues can it be uninstalled ?

I'm the PIAWireguard.py script I have set uk_manchester which isn't a region I've used before. Could that be changed to uk_london or uk_southampton and the changeserver command run ? Thanks

**Comment by FingerlessGlov3s** [comment]
Yeah you can remove the kmod version and go back to the normal version. I've not heard of anyone remove kmod for having issues. I keep a keen eye on it in the OPNsense IRC room. Once kmod is marked stable by Jason the WireGuard project owner it'll be used in OPNsense some time after that by default.

Yeah that would work well, changing between those 3 regions.

**Comment by MadTomT** [comment]
Hi. I'm up and running on uk_southampton and most of things seem to be working.
But I've got an issue with a couple of clients accessing some sites.
My phone and tablet access the same WiFi and get DHCP and DNS from the OpnSense.
My phone has has no issues online, but the tablet can't access some sites. If I take the tablet off the VPN it works fine. Any ideas what could cause that ? Thanks

**Comment by MadTomT** [comment]
Just had that issue updating this post on my tablet.

**Comment by FingerlessGlov3s** [comment]
What did you set your MSS maximum too in the end?

**Comment by MadTomT** [comment]
Hi. It's currently set to 1380.
How do you work out what it should be? Thanks
I've been able to load this page via the VPN, but had to come off it to reply.. thx

**Comment by MadTomT** [comment]
Just a quick thought. I'm using PPPoE for my WAN interface. Thanks

**Comment by FingerlessGlov3s** [comment]
Try lowering it to 1372, see if it makes any difference.

Your MSS rule looks like the following?

![image](https://user-images.githubusercontent.com/3495647/115971177-d846b500-a53e-11eb-9e16-f9fc163e9e31.png)

**Comment by MadTomT** [comment]
Hi, My screen does look like yours.
Changing it to 1372 has allowed some sites to work, but not others.
If I drop it to 1300 it seems to work better but does that affect performance ?

Thanks

**Comment by FingerlessGlov3s** [comment]
I wonder if the issue isn't MSS and it's something else going on.

Lowering it would affect performance yes, but you shouldn't need to have it that low.

**Comment by MadTomT** [comment]
Would the PPPoE MTU have any affect on this ? It is currently set at 1484, yet the calculated value is 1476. 

Any suggestions on how to work out what is causing this ?
Thanks again.

**Comment by FingerlessGlov3s** [comment]
It would!  I assumed the PPPoE you had was 1492, not 1476. This changes everything!

Since your connecting to PIA over IPv4, you need to set the MTU of WireGuard for PIA to 60 bytes less than your MTU on your WAN. So if your WAN MTU is 1476. We need to take 60 bytes off that which makes it 1416, so you need to set the MTU on the WireGuard interface to 1416 and then the maximum MSS then needs to be 40 bytes lower than that so 1376.

So end result is
PIA WireGuard MTU 1416
MSS Maximum of 1376

Try these values. Also it's worth checking your WAN MTU is 1476. You can check this easily by setting a device to go directly out of the WAN and then doing a Ping with a certain length with it set to do not fragment, examples below. If it pings your MTU is 1476, is it doesn't its lower.
Windows: ping -f -l 1448 1.1.1.1
Linux: ping -M do -s 1448 1.1.1.1

**Comment by MadTomT** [comment]
Thanks. I will check this in the morning and let you know how I get on.
I appreciate that help.

**Comment by MadTomT** [comment]
Morning. ping -f -l 1448 1.1.1.1 does return correctly, increasing this to 1456 and I get fragmentation.
I've set the PIA MTU & MSS values and all seems to be working fine.
Interestingly what ever I set the MTU in the WAN as soon as I click out of the field the calculated value is always 8 bytes less, is that normal ?  Thanks

**Comment by FingerlessGlov3s** [comment]
Sweet, sounds good that its now working nicely! Still working ok now?

The reason it takes off 8 bytes, is because its being cleaver and taking off the 8 bytes for PPPoE encapsulation.

Best thing to do is make sure your MTU should be 1476, by upping it and then testing it with ping. When you test it with ping you need to set the bytes length 28 bytes lower than the MTU.

**Comment by MadTomT** [comment]
All seems to be working well. 
I've had a look at mymold pfSense and the MTU on that is set as 1492. I'm tempted to try it. Would I then be able to set the PIA MTU ?to 1432 and MSS to 1392?

**Comment by FingerlessGlov3s** [comment]
I would say yes to MTU of 1432, but at PIA's side its 1420, so I wouldn't go higher than that. I asked PIA what their WireGuard MTU is and they said it'll be what ever the WireGuard default is which is 1420.

Yeah 1492 after PPPoE is usually the norm MTU.

**Comment by MadTomT** [comment]
Not sure what is going on, no changes have been made yet and the issue has returned.

WAN Gateway MTU 1476
WAN_PIAGW MTU & MSS not set

FIREWALL: SETTINGS: NORMALIZATION MSS 1376
VPN: WIREGUARD:LOCAL 1416

I don't understand why this has stopped.

**Comment by FingerlessGlov3s** [comment]
When the issue appears, are you able to ping the website that's effected?

**Comment by MadTomT** [comment]
I'm wondering if this is a DNS issue. opnsense is my DHCP & DNS server (unbound).
PIA is only used by Wifi devices, I've just tried going to bbc.co.uk and nothing happened.  So I tried to ping it with no response. Trying a DNS lookup also failed. I known that opnsense is resolving as I've tested it with nslookup. My firewall rule to route traffic via PIA is currently:

Protocol IPv4 *
Source OPT1WIFI net
Port * 
Desination *
Port *
Gateway WAN_PIAWG_IPv4
Schedule *

I'm assuming that is going to send all traffic via PIA including the DNS lookups which should be being done via opnsense.
Is there anyway to have DNS local before routing via PIA ?
Or am I looking in the wrong area ?

**Comment by FingerlessGlov3s** [comment]
DNS shouldn't be going to PIA unless your giving out external DNS address on your DHCP.

I recommend you change "Destination *" to "Destination !RFC1918" so you only route non private networks over the VPN.

It's also worth noting if your using PIA to consume streaming services, its recommended to use PIA's DNS servers. Which is 10.0.0.243, so give this IP out on your DHCP WiFi and then you'll should have two rules like this.


Protocol IPv4 *
Source OPT1WIFI net
Port *
Destination !RFC1918
Port *
Gateway WAN_PIAWG_IPv4
Schedule *


Protocol IPv4 *
Source OPT1WIFI net
Port *
Destination 10.0.0.243
Port *
Gateway WAN_PIAWG_IPv4
Schedule *

**Comment by MadTomT** [comment]
Sorry I've not used !RFC1918 before.. do I literally enter that into the Destination field ? What need to be set as the CIDR ?

**Comment by MadTomT** [comment]
Currently I'm providing 10.10.10.1 (opnsense) and 209.222.18.222 (PIA) which I belive may now be dead, so changed to 1.1.1.1
I've updated the rules

Protocol IPv4 *
Source OPT1WIFI net
Port *
Destination !RFC1918
Port *
Gateway WAN_PIAWG_IPv4
Schedule *

Protocol IPv4 UDP/TCP
Source OPT1WIFI net
Port *
Destination OPT1WIFI Address
Port 53
Gateway WAN_PIAWG_IPv4
Schedule *

**Comment by FingerlessGlov3s** [comment]
You'll need to create an alias called RFC1918 and put the RFC1918 networks in it.

The ! means invert selection, which is an option on the rule page.

Yeah 209.222.18.222 has/is been replaced with 10.0.0.243, which is DNS server on the actual PIA VPN server.

**Comment by FingerlessGlov3s** [comment]
Has that rules you've put in started to make anything work?

**Comment by MadTomT** [comment]
I've done that but something is messed up.. I'm still getting DNS issues with 10.10.10.1, and some sites like tumblr load but fail to allow me to log in. As soon as I'm off the VPN its fine.

**Comment by FingerlessGlov3s** [comment]
Add the firewall rule below and set the client DNS to 10.0.0.243. 
Have you got Unbound in forwarding mode?

Protocol IPv4 UDP/TCP
Source OPT1WIFI net
Port *
Destination 10.0.0.243
Port 53
Gateway WAN_PIAWG_IPv4
Schedule *

**Comment by MadTomT** [comment]
Unbound isn't in forwarding mode. I've added the new rule and PIA DNS is now working.
But I still have the issue with intermittent loading of sites.

**Comment by FingerlessGlov3s** [comment]
Does PIA DNS work every time, you query something different?

**Comment by MadTomT** [comment]
It appears to be working, I'm using an Android tablet via Wifi and checking DNS using an app. The DNS is automatically detected as 10.0.0.243 and looking up various hosts has worked fine. I dropped my MSS back to 1300 and now the browsing appears to be working again.

**Comment by FingerlessGlov3s** [comment]
I think it might be worth getting your WAN MTU back to 1492 if it support it.

**Comment by MadTomT** [comment]
Ok - I've backed up.. I'll try setting:
WAN MTU 1492
PIA MTU 1432
PIA MSS 1392

is that right ?

**Comment by FingerlessGlov3s** [comment]
WAN MTU 1492
PIA MTU 1420
PIA MSS 1380

PIA's maximum MTU for WireGuard is 1420, so we can't go higher than this at our end.

When the internet is working, you do get an PIA IP? https://ifconfig.co

Also is the gateway monitor in OPNsense reporting 0 loss?

**Comment by MadTomT** [comment]
ifconfig.co reports 143.244.36.66
DNS is resolving using PIA and so far webs sites are working and packet loss is 0%
I'll monitor it tonight and see what feedback I get.
Thanks for all you help, advise and support.

**Comment by FingerlessGlov3s** [comment]
Sounds good, with the below values you should hopefully get no issues.

WAN MTU 1492
PIA MTU 1420
PIA MSS 1380

**Comment by MadTomT** [comment]
Hello.. all seems to be well. No issues reported using the VPN.
Thanks for all the help
