### ISSUE TITLE
Changing PAI Username & Password

### ISSUE THREAD

**Issue by MadTomT** [FingerlessGlov3s/OPNsensePIAWireguard#16]
Hi.
I've created a new account on PIA, is it as simple as editing the piaUsername and piaPassword values in PIAWireguard.py and then restarting wireguard tp use the new credential ?

I can edit the file, but what needs to be restarted and how ?
Thanks

**Comment by FingerlessGlov3s** [comment]
Edit the piaUsername and piaPassword should do the trick

Then run `/conf/PIAWireguard.py debug changeserver` to make sure there's no errors :-)

**Comment by MadTomT** [comment]
That looks like it works thanks :)
