### ISSUE TITLE
Does Port forward option require a change if opnsense was on http?

### ISSUE THREAD

**Issue by cwesterfield** [FingerlessGlov3s/OPNsensePIAWireguard#17]
Everything is working great, so after a week of burn in I decided to try port forwarding. 

The only change I made was this:
```
piaPortForward = True # Only enable this if you know what you are doing
#piaPortForward = False # Only enable this if you know what you are doing
```
now if I run /conf/PIAWireguard.py debug it errors out

```
root@super-router:/conf # ./PIAWireguard.py debug
WGInstanceUUID: REMOVED
WGPeerUUID: REMOVED
WGInstance: REMOVED
WGPeer: REMOVED
Tunnel working - last handshake 26 seconds ago
Port not assigned, shall request port
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused
~~~
```

I was using http and have changed it to https. With it set to False, I get no errors.

**Comment by cwesterfield** [comment]
I'm a nonce. I didn't realize that I had to pick a server that allowed port forwarding, I assumed they all did. 

All is well now. Sorry to the inconvenience.

**Comment by FingerlessGlov3s** [comment]
Indeed that is the case, I did include it in the regions list to show if port forwarding is available.

`ListRegions.py` or `PIAWireguard.py listregions` can be used to list regions.

**Comment by FreakyBigFoot** [comment]
What did you do in opnsense to port forward once you picked a server that allowed it? I can't seem to get the firewall rule or port forwarding to work.

**Comment by cwesterfield** [comment]
> What did you do in opnsense to port forward once you picked a server that allowed it? I can't seem to get the firewall rule or port forwarding to work.

Under Nat > Port forwarding

<img width="1608" alt="image" src="https://user-images.githubusercontent.com/24945480/226372156-0b0992fd-c9c1-4654-8f59-6bd3e3374b67.png">
