### ISSUE TITLE
OPNsense 21.7.4 PIA Gateway stuck on pending.

### ISSUE THREAD

**Issue by dschaper** [FingerlessGlov3s/OPNsensePIAWireguard#19]
Using the latest release code (with DIP support) on 21.7.4. 

After the upgrade reboot I'm seeing the PIA Gateway stuck on Pending. 

![Screenshot 2021-10-29 110501](https://user-images.githubusercontent.com/2782850/139481950-73369ca9-771e-4ee3-86e1-215523ca8db2.png)

Routes:
```plain
root@OPNsense:~ # route get 10.6.128.1
   route to: 10.6.128.1
destination: 10.6.128.1
        fib: 0
  interface: wg2
      flags: <UP,HOST,DONE,STATIC>
 recvpipe  sendpipe  ssthresh  rtt,msec    mtu        weight    expire
       0         0         0         0      1420         1         0
```
Pings:
```plain
root@OPNsense:~ # ping 10.6.128.1
PING 10.6.128.1 (10.6.128.1): 56 data bytes
64 bytes from 10.6.128.1: icmp_seq=0 ttl=64 time=61.682 ms
64 bytes from 10.6.128.1: icmp_seq=1 ttl=64 time=61.026 ms
64 bytes from 10.6.128.1: icmp_seq=2 ttl=64 time=60.529 ms
^C
--- 10.6.128.1 ping statistics ---
3 packets transmitted, 3 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 60.529/61.079/61.682/0.472 ms
```

debug:
```plain
root@OPNsense:~ # /conf/PIAWireguard.py debug
WGInstanceUUID: 3bfc14df-7d1a-4c39-8bf4-c4952ce7055f
WGPeerUUID: a7c1a864-41f3-4471-9cdb-44f407d1c9ed
WGInstance: 24T9+KH++1lWpueIB/uQJf4uUJO7cjQqdb5Cr4m01wE=
WGPeer: LSrbsD/KJHy3fFWCLcCyFyPxP0giCu4/RbjO866OoiQ=
Tunnel working - last handshake 56 seconds ago
```

My other `wg` interfaces are running without any loss.

**Comment by FingerlessGlov3s** [comment]
Has a "Apply" button appear in the gateway's page?

**Comment by dschaper** [comment]
None that I see. There's no `dpinger` service running for this interface though.

**Comment by dschaper** [comment]
Everything was working fine before the upgrade and reboot.

**Comment by FingerlessGlov3s** [comment]
When did you upgrade the script? Although this shouldn't effect the gateway. Just want to rule out the latest script amendments 😊

**Comment by dschaper** [comment]
Heh, I did the upgrade after the reboot when I saw the gateway wasn't coming up. Wanted to make sure there weren't any changes that were made for the new point release of OPNsense.

**Comment by FingerlessGlov3s** [comment]
I'll do some testing later on 21.7.4. See if it happens to me also.

**Comment by dschaper** [comment]
For some reason the Gateway became disabled. Enabling the Gateway has everything back to working again. That's a bit odd since the Disabled checkbox was unticked.

**Comment by FingerlessGlov3s** [comment]
Tested upgrade with latest script on a VM from a VM at 21.7.1 to 21.7.4 the problem didn't surface, I also checked my home router which is running 21.7.4 and it's ok as well.

Yeah it does sound like an isolated issue.
