### ISSUE TITLE
Is it possible to change the 5 minute check ?

### ISSUE THREAD

**Issue by MadTomT** [FingerlessGlov3s/OPNsensePIAWireguard#20]
Hi,

As per subject is it possible to change the 5 minute up check ?
Thanks

**Comment by FingerlessGlov3s** [comment]
Hi MadTomT,

Indeed you can, although I wouldn't suggest going longer than 10 minutes if your using port forwarding.

Simple Explaination;
There's two checks both of these are local. One checks if WireGuard is still getting handshakes to the PIA server. The other if PF is enabled, tells PIA that you want to keep the port, to stop it going stale, which I've been told needs to be told every 10-15 minutes or so.

Detail Explaination;
When the script runs, it'll check the handshake of wireguard, and if its within the last 190 seconds, we assume the tunnel is working fine, if its 191 seconds or longer ago we shall assume the connection is lost and attempt to reconnect to a new PIA server. Code: https://github.com/FingerlessGlov3s/OPNsensePIAWireguard/blob/b7b4c09c7eca651ed162de2614d14e02885577fb/PIAWireguard.py#L373
As for port forwarding if enabled, once a port is given too us by PIA, we need to refresh it every 10-15 minutes. So we do 10 minutes to be extra careful, not to loose the port. ttps://github.com/FingerlessGlov3s/OPNsensePIAWireguard/blob/b7b4c09c7eca651ed162de2614d14e02885577fb/PIAWireguard.py#L709
The port is also only valid for 60 days or so, even with the refreshing, so we also check to make sure its not about to expire and if it is request a new port. https://github.com/FingerlessGlov3s/OPNsensePIAWireguard/blob/b7b4c09c7eca651ed162de2614d14e02885577fb/PIAWireguard.py#L704

I hope this helps to answer your question :-)

**Comment by FingerlessGlov3s** [comment]
STALE

**Comment by MadTomT** [comment]
Sorry I should have replied to this.. I've now got it working checking every 2 minutes.

Thanks
