### ISSUE TITLE
wireguardserver generateToken request failed non 200 status code - Trying to get PIA token on US server

### ISSUE THREAD

**Issue by SkinnyV** [FingerlessGlov3s/OPNsensePIAWireguard#21]
Hello,

I am trying to set up PIA VPN on the latest version of opnsense but it fail at step 5 ''/conf/PIAWireguard.py debug'' with this error on SSH:

WGInstanceUUID: *
WGPeerUUID: *
WGInstance: *
WGPeer: *
metaServer
newjersey440
191.96.185.9
wgServer
newjersey440
191.96.185.248
wireguardserver generateToken request failed non 200 status code - Trying to get PIA token

I saw that there was an old issue with the same error and that it was supposed to be fixed, but I am getting this on all US PIA server I tried.

Thank you

**Comment by FingerlessGlov3s** [comment]
Sounds like an issue authenticating, can you make sure your provided login credentials are correct. That error is outputted when PIA login token generation doesn't return correct.

https://github.com/FingerlessGlov3s/OPNsensePIAWireguard/blob/2f972edf02c691989b46d5868bebd42bc41864d7/PIAWireguard.py#L546

**Comment by SkinnyV** [comment]
Woah, that is fast support! And yeah, its a bit awkward but you were right and it was a problem with my credentials. Sorry for bothering for such a n00b mistake but I instantly assumed it had to be problem somewhere else considering the past issue I found had the same message.

In any case, thank you!
