### ISSUE TITLE
Second WG connection fails with "addkey request non 200 code"

### ISSUE THREAD

**Issue by panks21** [FingerlessGlov3s/OPNsensePIAWireguard#24]
Hi 
First of all, thanks for the great script. Starred already

My first WG to Mumbai server is running fine for a few days and now I am trying to add Ireland as a second WG but facing the issue. I followed the steps issue #8 but hard luck

Following is the error I hit

`WGInstanceUUID:
WGPeerUUID:
WGInstance:
WGPeer:
WGPeer is blank but this isn't an issue
metaServer
dublin405
193.56.252.2
wgServer
dublin405
193.56.252.8
Your PIA Token (Meta), DO NOT GIVE THIS TO ANYONE
{
    "status": "OK",
    "token": "9fSUABziDpwH_E2yieg5oFmAacCAQ_c83iskvJ4xDhARm5ZMfrpD8tjaATVCrO5qDkveFbFIVmtGePwvQr4cCbbu2OfigO0WZRYIeSU9vGn4sKXJVQUaiXXDUcY="
}

wireguardserver addKey request failed non 200 status code - Trying to add instance public key to server in exchnage for connection information
`

I searched this in the code and found it on line 575 but cant make out how to fix this

I have done following

1) Made a copy of PIAWireguard.py to PIAWireguardire.py
2) Made a copy of PIAWireguard.json to PIAWireguardire.json
3) Edited the python script to read PIAWireguardire.json
4) chmod +x /conf/PIAWireguardire.py
5) service configd restart
6) /conf/PIAWireguardire.py debug

**Comment by panks21** [comment]
Yeah.. I did to PIA_IRE and 51816 respectively

**Comment by panks21** [comment]
Here are the contents of new json file

cat /conf/PIAWireguardire.json 
{
    "opnsenseURL": "https://127.0.0.1",
    "opnsenseKey": "PqZmsjCc47ARErcv/e60ev05vaAXEDtq2cU/aypusSBsqK8b1Ac+mIKPm+6DKNdNbn0YKLzdpOB1n7lx",
    "opnsenseSecret": "dutjGu590Y/drnVmKiiOTGmC5FwapNNiPiTF73RJySOrSCMtwTzEWPxO8oM5xO6keMYUEnUYXsLvtQG1",
    "opnsenseWGName": "PIA_IRE",
    "opnsenseWGPort": "51816",
    "piaUsername": "<user-name>",
    "piaPassword": "<password>",
    "piaRegionId": "ireland",
    "piaDipToken": "",
    "piaPortForward": false,
    "piaUseDip": false,
    "tunnelGateway": null
}

**Comment by panks21** [comment]
It was a bit weird but the issue is fixed. Apparently it doesn't like the underscore in the name
Changed to PIAIRE from PIA_IRE and it worked...

**Comment by FingerlessGlov3s** [comment]
Added check for the `opnsenseWGName` in commit https://github.com/FingerlessGlov3s/OPNsensePIAWireguard/commit/236ef68c43c70fffae9018b813a7a8691f9ab968
