### ISSUE TITLE
VPN not working after update to 22.1.10

### ISSUE THREAD

**Issue by Llamrei80** [FingerlessGlov3s/OPNsensePIAWireguard#25]
Hi,

after the update to OPNsense 22.1.10 the VPN Gateway is not created and therefore can't be used in firewall rules.

In the Wiregaurd settings there is a Endpoint configured and there is a Handshake been untertaken, so it seems the script partly works.

**Comment by Llamrei80** [comment]
Set it up years ago, always worked fine.

**Comment by FingerlessGlov3s** [comment]
Has the interface change?  I assume it was wg0 before, I can't see why it would have changed though.

SSH in and do `/conf/PIAWireguard.py debug`, can you show the output of the script in here please :-)

**Comment by FingerlessGlov3s** [comment]
The script is failing to connect to the web server on OPNsense, have you changed the port it listens on?

TCP port for WebUI is listed here `System: Settings: Administration`
