### ISSUE TITLE
Update the server list URL

### ISSUE THREAD

**Issue by chromecapone** [FingerlessGlov3s/OPNsensePIAWireguard#26]
I did this manually, but for the benefit of the community, please consider updating the server list URL from: 
`https://serverlist.piaservers.net/vpninfo/servers/v4` to `https://serverlist.piaservers.net/vpninfo/servers/v6` 

There seems to be more servers in more locations listed. The scripts seems to work just fine with the new server list. I was able to use multiple US servers that are on v6 that are not included in v4, without issue.

**Comment by FingerlessGlov3s** [comment]
Just comparing the output, the list of regions is the same but they list more than one server for some regions for each protocol, plus some extra metadata.

I shall ask upstream and find out what the difference is between them, and then I'll migrate to v6 and make sure it can cope with the multiple servers return for some of the region's protocols.

**Comment by FingerlessGlov3s** [comment]
Updated to new server list version. https://github.com/FingerlessGlov3s/OPNsensePIAWireguard/commit/3fdd6ee3f704318a00936771b58c3b9175f0a5c2
