### ISSUE TITLE
Error-Message since Update OPNsens to 22.7.5 on 5th Oct

### ISSUE THREAD

**Issue by duderio** [FingerlessGlov3s/OPNsensePIAWireguard#27]
Hello,

thank you for the manual. Since OPNsense Update 22.7.5  few days ago, the WG-Conncection failed.
Bevor everything was fine.

Error-Message executing /conf/PIAWireguard.py:

"searchServer request failed non 200 status code - listing wireguard instances"

Update OPNsense from 22.7.4 to 22.7.5 updated Python from 3.9.13 to 3.9.14.

Thank you.
Kind regards

**Comment by FingerlessGlov3s** [comment]
Hey, I haven't updated any of my instances yet. I shall do that today and look in to this 😊

**Comment by FingerlessGlov3s** [comment]
Just tested this on my OPNsense now it's upgraded to 22.7.5 and it's not erroring.

I assume your using the latest version of the script. Also can you run the script in debug `/conf/PIAWireguard.py debug` and put the output in here.

**Comment by duderio** [comment]
Ok. I use the latest version of the script.
I checked my settings in OPNsense. Last change was setting the WebGUI port to 55443 because HAProxy is using 443.
May this cause the problem?

Output from /conf/PIAWireguard.py debug is same as above

searchServer request failed non 200 status code - listing wireguard instances

/conf/ListRegions.py - Error is:

/conf/ListRegions.py: import: not found
/conf/ListRegions.py: import: not found
: not foundegions.py:
/conf/ListRegions.py: piaServerList: not found
: not foundegions.py:
/conf/ListRegions.py: s: not found
/conf/ListRegions.py: 7: Syntax error: "(" unexpected

Python Online Compiler is ok - no error.

**Comment by duderio** [comment]
Hmmm...it is the port.
Changed it in the json file.

"opnsenseURL": "https://127.0.0.1:55443",

Now script is working.
Thank you!

**Comment by FingerlessGlov3s** [comment]
Yes, if you change the default webui port, you need to reflect that in the script ☺
