### ISSUE TITLE
Not working on OPNSense 23.1_6?

### ISSUE THREAD

**Issue by chromecapone** [FingerlessGlov3s/OPNsensePIAWireguard#29]
Uploaded the newest PIAWireguard.py to the router. Did the chmod +x /conf/PIAWireguard.py and tried to run PIAWireguard.py. I got an error, "/conf/PIAWireguard.py: 8: Syntax error: newline unexpected (expecting word)"

I think 23.1_6 is running an newer version of python... likely the issue? 

Also, noticed the following with ListRegions.py file.

1. If I go to the online complier  (https://www.programiz.com/python-programming/online-compiler/) and run the code. The following error is generated: Traceback (most recent call last):
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'requests'

2. The ListRegions.py file is showing an older version of the server list. https://serverlist.piaservers.net/vpninfo/servers/v4 instead of https://serverlist.piaservers.net/vpninfo/servers/v6

**Comment by FingerlessGlov3s** [comment]
Hi,

I've tested this on my 23.1 OPNsense and I'm not getting the error you are.
```
root@OPNsense:/conf # uname -a
FreeBSD OPNsense.localdomain 13.1-RELEASE-p5 FreeBSD 13.1-RELEASE-p5 stable/23.1-n250372-c4ad069e50a SMP amd64
root@OPNsense:/conf # /conf/PIAWireguard.py debug
WGInstanceUUID: a64355ad-a989-43c8-89ca-b9299a8a743e
WGPeerUUID: 2b05c3bf-e9fe-41ee-a8b2-450ff17b1c8d
WGInstance: BojX0PBwKA0Z/bVKDQzdBdFkkgapcwUKJMNqJJYkGy4=
WGPeer: iDPxICPyn6RLid2HT4Jd00mc/uBxkxF4yGumDO2OtGI=
Tunnel working - last handshake 31 seconds ago
```

I shall also update the url in the `ListRegions.py` shortly

**Comment by FingerlessGlov3s** [comment]
Please run the below and try again please

`fetch -o /conf/PIAWireguard.py https://raw.githubusercontent.com/FingerlessGlov3s/OPNsensePIAWireguard/main/PIAWireguard.py`

**Comment by chromecapone** [comment]
root@OPNsense:/conf # uname -a
FreeBSD OPNsense.localdomain 13.1-RELEASE-p5 FreeBSD 13.1-RELEASE-p5 stable/23.1-n250372-c4ad069e50a SMP amd64

root@OPNsense:/conf # /conf/PIAWireguard.py debug
/conf/PIAWireguard.py: 8: Syntax error: newline unexpected (expecting word)

After I ran this command:
fetch -o /conf/PIAWireguard.py https://raw.githubusercontent.com/FingerlessGlov3s/OPNsensePIAWireguard/main/PIAWireguard.py

Then this:
/conf/PIAWireguard.py debug

There's the output:
WGInstanceUUID: 27dd52fe-5026-4372-adeb-f871c9a17709
WGPeerUUID: f6c853f6-0735-4a5c-bc2e-a44b3dcfc42c
WGInstance: iV5F008UYQFpozCaRo+8UxDOVH6rjQF+RE/Jw6N/sgo=
WGPeer: 9WgvVlIK4M6oeICQbjCTUCxvZrh/DOqZdGgGMecQg2E=
Tunnel working - last handshake 37 seconds ago

So, looks like the PIAWireguard.py that I uploaded to the router was buggered. Sorry!

**Comment by TripitakaBC** [comment]
Can confirm that I am also getting the error #1 that @chromecapone mentions; 
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'requests'

**Comment by FingerlessGlov3s** [comment]
@TripitakaBC  does it still happen after running the following?

```
fetch -o /conf/PIAWireguard.py https://raw.githubusercontent.com/FingerlessGlov3s/OPNsensePIAWireguard/main/PIAWireguard.py
```

**Comment by panks21** [comment]
@FingerlessGlov3s The issue is with the ListRegions.py

**Comment by TripitakaBC** [comment]
I only copied the code and put it into the online python tool. I get the same running it on my local machine though. I’m a little confused about where to run the command below as I’m not yet working in the shell to opnsense.

**Comment by FingerlessGlov3s** [comment]
https://paiza.io/en/projects/new?language=python3

^ Please try this online python tool linked above.

**Comment by TripitakaBC** [comment]
That one worked perfectly! Thank you!
