### ISSUE TITLE
Authentication Failed during "PIAWireguard.py debug" step

### ISSUE THREAD

**Issue by cyclyte** [FingerlessGlov3s/OPNsensePIAWireguard#30]
Running on 23.1_6

After running "PIAWireguard.py debug" I get this line - **wireguardserver generateToken request failed non 200 status code - Trying to get PIA token**.
I added an extra print statement to the script to see the response text for the request - 
**text = {
    "status": "ERROR",
    "message": "authentication failed"
}**
The odd thing is that the username and password I placed in the .json file is correct; I was using it to connect with OpenVPN and I tested logging into the PIA site a few times.  I'm positive that it's right.
Is it possible that a separate username/password is needed?  Otherwise, I don't understand what I'm doing wrong.

**Comment by FingerlessGlov3s** [comment]
You are using the right credentials, try resetting the password and double check for any spaces in the password/username value in the JSON.

**Comment by cyclyte** [comment]
Resetting the password worked.  Thanks for the help.
