### ISSUE TITLE
Can we auto port forward? I also keep losing my port forwarding for some reason

### ISSUE THREAD

**Issue by FreakyBigFoot** [FingerlessGlov3s/OPNsensePIAWireguard#33]
So when I connect to PIA and get a random port, I seem to have the port not available after some time. I also realized you get a random one. Can we not automate the port given by wgx_port.txt to update the alias used for port forwarding?

**Comment by FreakyBigFoot** [comment]
Oh actually I found this..

`opnsenseWGInstance = ""`

I guess I need to define that. Testing now.

**Comment by FreakyBigFoot** [comment]
I guess when does the port get added/updated to the firewall rule PIA_PORT? It's not updating the alias.

**Comment by EeroV** [comment]
hi,

it will update alias, if port forward changes.

Eero

**Comment by FingerlessGlov3s** [comment]
You only need to change settings in the json, `opnsenseWGInstance` doesn't require editing.

PIA only keep the port open, if you send a keepalive to their port forwarding API every 10 minutes or less. If you have set the Cron to be 10 minutes or longer, it's probably sending the keep alive after the required window.

The Cron should be every 5 minutes.

If the script detects a new port is required it will update the alias and the txt file.

**Comment by FreakyBigFoot** [comment]
That's the thing. It's not updating the rule. I've had the port change twice now.

**Comment by FingerlessGlov3s** [comment]
So it's not updating the alias on OPNsense?

**Comment by EeroV** [comment]
make sure that api key has all needed access?

**Comment by FreakyBigFoot** [comment]
Yeah it's not updating the alias at all. Let me see what the API key has permissions to. Didn't know there was a different level of access for API keys.

**Comment by iShark5060** [comment]
you want these permissions:

```
Scroll down to you see "Effective Privileges", you want to give it the following permissions
Firewall: Alias: Edit
Firewall: Aliases
System: Static Routes
VPN: Wireguard
```

**Comment by FreakyBigFoot** [comment]
Will having admin rights not just provide all these?

**Comment by iShark5060** [comment]
the user you have created should NOT have admin rights.

**Comment by FingerlessGlov3s** [comment]
If you do `/conf/PIAWireguard.py debug changeserver`
See what it says when it comes to the port forwarding logs.

**Comment by EeroV** [comment]
please note that all servers does not support port forwarding..

**Comment by FreakyBigFoot** [comment]
I have port forwarding working. This server supports it. I've had to manually update the alias. 

```
Saved wireguardSignature and payload to /tmp/wg1_piaportforwardsignature
CurrentPortInAlias: 57022
Required Port: 43050
Ports don't match shall correct the Alias


But my alias didn't update..

**Comment by FingerlessGlov3s** [comment]
Delete the alias, and see if it recreates it, then test it changing again.

**Comment by FreakyBigFoot** [comment]
It re-created the rule but it's empty.

**Comment by FreakyBigFoot** [comment]
I don't need to update the variale `opnsenseWGInstance ` in PIAWireguard.py do I?

**Comment by FreakyBigFoot** [comment]
Also does it matter that the opnsenseURL is https://10.0.0.1 ? Does it need to be a valid URL or something?

**Comment by FingerlessGlov3s** [comment]
If the URL is wrong the script will fail at the beginning.
You do not need to edit any part of the script, so please don't do that.

Can you make sure you have the latest version of the python script. 😊

**Comment by FreakyBigFoot** [comment]
I have the latest. I've been running this setup for about a month. This is the only issue I'm running into :/

**Comment by FreakyBigFoot** [comment]
Hey that worked... I'm not sure why that worked but thanks @FingerlessGlov3s . I really appreciate this project.
