### ISSUE TITLE
How to setup a kill switch

### ISSUE THREAD

**Issue by delta-whiplash** [FingerlessGlov3s/OPNsensePIAWireguard#34]
Hello, I am using an opnsense firewall with your script I have two lan :
- piaNET => routed to WAN_PIAWG
- serverNET => routed to WAN

Sometimes when I reboot my firewall to pass some updates the WAN_PIAWG_IPv4 disappears and my public IP is exposed 
to fix this I have to run manually `/conf/PIAWireguard.py debug` or wait 5 minutes 
I tried a lot of firewall rules to handle this specific situation but no one worked 
Could you please help me

**Comment by EeroV** [comment]
is the service enabled?

**Comment by delta-whiplash** [comment]
what service ?

**Comment by iShark5060** [comment]
Point 3) and 5) in the tutorial

**Comment by EeroV** [comment]
wireguard?

la 1. huhtik. 2023 klo 15.23 delta-whiplash ***@***.***)
kirjoitti:

**Comment by delta-whiplash** [comment]
I think yes

**Comment by FingerlessGlov3s** [comment]
Hi,

This is quite simple to fix, and put a sort of "kill switch" in.

1. Edit the route that's allowing the traffic on the LAN, or which ever interface it is.
Add this traffic tag value `NO_WAN_EGRESS` to the rule, it's in the advanced section when you press edit on a rule. This will tag the traffic as it passes through OPNsense's filters so we can use that tag later on.
![image](https://user-images.githubusercontent.com/3495647/229294855-65807dde-4528-4b95-a9f7-cc2ee3ca0214.png)

2. Create a rule on your WAN interface, as seen below in this screenshot.
Essentially we're blocking outbound traffic where it's been tagged with `NO_WAN_EGRESS`, so if the traffic tries to leave the WAN interface, it'll be blocked and therefore kill switch 😊
![image](https://user-images.githubusercontent.com/3495647/229295022-00ea5826-8d99-4910-857a-0d7cd513efae.png)

**Comment by delta-whiplash** [comment]
this rules will not block my serverNET ?

**Comment by FingerlessGlov3s** [comment]
> this rules will not block my serverNET ?

No, because that traffic wouldn't have been set the `NO_WAN_EGRESS` tag on the allow rule for that traffic.

**Comment by delta-whiplash** [comment]
OH YES I SEE thank you am gonna try this this evening

**Comment by delta-whiplash** [comment]
OMG your a genius it worked I disabled my PIA gateway and there is no internet on any of my machines
