### ISSUE TITLE
VPN working, but nothing using it.

### ISSUE THREAD

**Issue by purplepotables** [FingerlessGlov3s/OPNsensePIAWireguard#35]
Hello,
I have followed the guide and the linked opnsense guide from step 7, but none of my devices seem to be using the tunnel. I have even gone as far as to restore to a previous image and try again with the same result. Do you have any thoughts or guidance?

**Comment by FingerlessGlov3s** [comment]
Does the PIA Gateway show as up and the monitoring is showing a rrt time? 

Example
![image](https://github.com/FingerlessGlov3s/OPNsensePIAWireguard/assets/3495647/3b985e20-4f2e-4572-a492-8d681eea2bcf)

**Comment by FingerlessGlov3s** [comment]
Show me a screenshot of your LAN rules, and highlight the one you believe should be working and isn't 😊

**Comment by purplepotables** [comment]
I'm not really sure which one is working. I'm wondering if my alias is wrong. When I hover over the RFC1918_Networks, it shows the subnets that the linked guide had input, 192.168.0.0/16 is one of them. The subnet for my lan is 192.168.100.0/24.
![Capture0](https://github.com/FingerlessGlov3s/OPNsensePIAWireguard/assets/95435443/dc31791c-e630-46d3-bb26-2ac9d6884b06)

**Comment by FingerlessGlov3s** [comment]
So when traffic hits the interface, it evaluates the rules top to bottom, so it's matching `Default Allow LAN to any rule", and using that to allow the traffic out of the default gateway.

That bottom PIA rule needs to become before that rule. and the top most PIA rule isn't required and can be deleted.

**Comment by purplepotables** [comment]
I have moved that rule to the top and applied the change and rebooted, but when I lookup the public ip of the machines on my network they still resolve to my non-vpn ip.

![image](https://github.com/FingerlessGlov3s/OPNsensePIAWireguard/assets/95435443/025f5c53-5674-4b63-8a10-0d98606645a6)

**Comment by FingerlessGlov3s** [comment]
I assume those two ALIAS are correct?

`WG_VPN_Hosts` should contain for example;
 - 192.168.0.102`

`RFC918_Networks` should contain the following;
 - `10.0.0.0/8`
 - `172.16.0.0/12`
 - `192.168.0.0/16`

If those are correct, what does your Outbound NAT look like?

**Comment by purplepotables** [comment]
That is probably where my mistake is. I have them both set to networks with a content of my subnet (192.168.100.0/24)

![image](https://github.com/FingerlessGlov3s/OPNsensePIAWireguard/assets/95435443/ef6121f7-11fa-48bb-8006-08ecc02ff30f)

**Comment by purplepotables** [comment]
My outbound nat is:

![image](https://github.com/FingerlessGlov3s/OPNsensePIAWireguard/assets/95435443/22b3044a-34c5-43d6-93ab-7ef61f0d5d1b)

**Comment by purplepotables** [comment]
Yes, .21, I think.

**Comment by purplepotables** [comment]
Actually, I think that fixing the RFC1918 alias fixed it. It is resolving to my pia now. THANK YOU!

**Comment by FingerlessGlov3s** [comment]
Problem is now fixed.
