### ISSUE TITLE
Interface out errors 

### ISSUE THREAD

**Issue by Guruleenyc** [FingerlessGlov3s/OPNsensePIAWireguard#36]
I followed all the steps the WG Gateway is online, but I'm seeing a lot of interface out errors on it and it does not seem to be passing traffic. Any ideas?

**Comment by FingerlessGlov3s** [comment]
Hey,

Is the gateway online or does it show latency of the gateway?

You shouldn't be getting interface errors, try doing `changeserver`, if it's still happening.

**Comment by FingerlessGlov3s** [comment]
Closing due to being stale.
