### ISSUE TITLE
Command Not Found Error

### ISSUE THREAD

**Issue by NicholasLambell** [FingerlessGlov3s/OPNsensePIAWireguard#38]
When trying to run `/conf/PIAWireguard.py debug` as per the instructions I received a "/conf/PIAWireguard.py: Command not found." error. The solution I found was to add `python3` to the start of the command to run the script directly under python. I also had to add this to the `command` line of 'actions_piawireguard.conf', as the cron task was otherwise failing.

I'm on what is basically a clean install with with no explicit OS modifications. Versions are reported as `OPNsense 23.7.3-amd64` and `FreeBSD 13.2-RELEASE-p2` in the main dashboard. I've also confirmed via `which python3` that the location matches `/usr/local/bin/python3`.
This seems to be the same as described in #4 but since it's closed and quite old I opened a new issue.

**Comment by FingerlessGlov3s** [comment]
The script is set to use `/usr/local/bin/python3` using [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)). This will be used long as the file is marked a executable in the file permissions. Are you use you added execute permission?

Run `ls -l /conf/PIAWireguard.py` and copy n paste back your results.

**Comment by NicholasLambell** [comment]
Script should definitely be executable as I set permissions with `chmod +x /conf/PIAWireguard.py` as per the instructions. This is somewhat also confirmed by tab completion filling the file which it doesn't when not executable.
Output from the ls command is `-rwxr-xr-x  1 root  wheel  41664 Sep 13 21:37 /conf/PIAWireguard.py`.

Also screenshot:
![image](https://github.com/FingerlessGlov3s/OPNsensePIAWireguard/assets/12807795/1a07ca6c-3b51-4fe2-8c89-4f4f099b2808)

**Comment by FingerlessGlov3s** [comment]
Can you run `grep python /conf/PIAWireguard.py` and report back the output please. Something isn't right with your file. 🤔

**Comment by FingerlessGlov3s** [comment]
I'm starting to think it's something weird with the file.

You can use `fetch` command to download the file directly from GitHub. Could you try that it do you need me to create the full command for you!

**Comment by NicholasLambell** [comment]
Just did a basic `fetch https://raw.githubusercontent.com/FingerlessGlov3s/OPNsensePIAWireguard/main/PIAWireguard.py` and set executable again which fixed it! 🎉 

I did a `file` command on files which confirmed the old one had Windows CRLF line terminators and new one doesn't. I even read a few things that said to make sure you had `\n` terminators but thought it looked fine when I checked before 🤦 
I guess git was doing its auto terminator translation stuff and I basically just uploaded the windows type file to the server. Good to get figured out at the very least 😄

**Comment by FingerlessGlov3s** [comment]
Bloody windows 🤣.

I have thought about updating the instructions to use fetch instead for the files apart from the json.

Maybe I should 🤔

**Comment by FingerlessGlov3s** [comment]
Yeah I use WSL for all linux stuff on my PC, SCP n all.

I've updated the guide in the below commit, which will stop anyone having the issue in the future. I would tell people to edit the json on OPNsense, but freebsd and vi can have some odd issues due to keymappings between windows/linux and freebsd, so either to let people do it locally and then copy it across. Since that'll stop them having issues.
https://github.com/FingerlessGlov3s/OPNsensePIAWireguard/commit/5300f9d403700d01e9d8c1edc5512e134df24268

**Comment by FingerlessGlov3s** [comment]
Issue has been resolved and with the updated README, hopefully shouldn't hit the problem anymore.
