### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by cheechie** [FingerlessGlov3s/OPNsensePIAWireguard#4]
When i get to this step.  

Run the following commands
chmod +x /conf/PIAWireguard.py
service configd restart
/conf/PIAWireguard.py debug  ---- I get "/conf/PIAWireguard.py: Command not found."

Any ideas?  I have copied the file to the correct folders.

**Comment by kumy** [comment]
@cheechie to help next users, what was your issue?
