### ISSUE TITLE
Port Alias Not Being Updated

### ISSUE THREAD

**Issue by ajtatum** [FingerlessGlov3s/OPNsensePIAWireguard#40]
For some reason, the port alias isn't updated. If I go to VPN > Wireguard > Status and look at the PIA Wireguard interface it shows, for example, 51815.  However, if I go to Firewall > NAT > Port Forward and look at the Port Alias "PIA_PORT" and click to view what port that is, it will show a different number, for example, 47192. However, if I manually run /conf/PIAWireguard.py debug changeserver from the Terminal it updates the Port Alias. So, it seems like there's an issue with the Cron Job nnot running appropriately or something,

I am running OPNsense 23.7.4.

**Comment by FingerlessGlov3s** [comment]
`VPN > Wireguard > Status` is the local port of the WireGuard service, it's not the port of the Forwarded port from PIA.

Your OPNsense will use port `51815` to connect to port `1337` on the PIA server to form the WireGuard tunnel. Then within that the port `47192` will be forwarded, to your given 10.x.x.x address.
