### ISSUE TITLE
Conneting to multiple servers

### ISSUE THREAD

**Issue by MonkeyGoneWIld** [FingerlessGlov3s/OPNsensePIAWireguard#42]
Is it possible to set up multiple wireguard connections using the script?

I used to have a multiple connection setup in Opnsense on a different VPN that used a fixed IP address for OpenVPN but I am not sure how to do it with the script on PIA.

**Comment by blackthroat** [comment]
@MonkeyGoneWIld Yes, I'm currently running 7 tunnels without issue. Basically create multiple copies of the script and JSON files, one for each tunnel:

![image](https://github.com/FingerlessGlov3s/OPNsensePIAWireguard/assets/25038086/e8613261-6cf1-48c4-956c-983a7716fe2b)

**Comment by MonkeyGoneWIld** [comment]
Worked Perfectly, Thank you for your help.
