### ISSUE TITLE
PIA_WG gateway is stuck offline.

### ISSUE THREAD

**Issue by Tig4rx** [FingerlessGlov3s/OPNsensePIAWireguard#43]
I am running OPNSense as a VM in Proxmox, recently I updated from 23.1.11_2 -> 23.7.6 and had no issues after the reboot. Installed zenarmor applied to my LAN interface. Had no issues until I rebooted the firewall to increase the memory allocation, now the PIA_WG gateway is just offline, I tried to unlink my VM interface from zenarmor, rebooted the firewall, and updated the PIAWireguard.py but to no avail.

PIA wg tunnel seems to be fine with recent handshakes showing.

**Comment by Tig4rx** [comment]
Running /conf/PIAWireguard.py debug changeserver returns this error after showing this

> Saved wireguard server information to /tmp/wg2_piaserverinfo
> Saved server_vip to /tmp/wg2_router
> Wait 5 seconds for new WireGuard server to apply before port forwarding


> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='hongkong402', por                                                                    t=19999): Max retries exceeded with url: /getSignature?token=PWRfduz2rig%2B9igqn                                                                    F%2B0qStnB_kU_qDeauITmco4ipMm%2B6rnq_E8UQ8mL%2ByE_rxFh%2BK5Di5mNJy1JvXJxyUCBU1lW                                                                    NlzU40X4u9jAt5Rn0GzvnkZLR70HFhq40E%3D (Caused by NewConnectionError('<urllib3.co                                                                    nnection.HTTPSConnection object at 0x84f5cb1c0>: Failed to establish a new conne                                                                    ction: [Errno 60] Operation timed out'))

**Comment by FingerlessGlov3s** [comment]
I wonder if the script needs an update to support 23.7.6, probably come API changes I need to do maybe 🤔. Shall have a look at this when I get time.

**Comment by bedub1** [comment]
I’m experiencing the same issue. Haven’t had a chance to review the logs, will check my system later.

**Comment by Skylinar** [comment]
Im facing the exact same issue on 23.7.6. After update it came up normalle, no issues. Yesterday I had to reboot and now the gateway is not willing to come online but i never changed something since 2 month and it was working through several reboots. Could someone figure out whats the issue? Maybe it would be good to point out in the readme, that it is not working with 23.7.6.
