### ISSUE TITLE
up check cron job putting gateway offline after update to Opnsense 23.7.6 and wireguard 2.3

### ISSUE THREAD

**Issue by PatSloan** [FingerlessGlov3s/OPNsensePIAWireguard#44]
I used this setup for my wireguard PIA access now with opnsense 23.7.6 update, which includes wiregard 2.3 this setup no longer works.   I had to revert back to wireguard 2.1.   works fine on wireguard 2.1 after reboot.

**Comment by fabricemrchl** [comment]
Hi,
Same issue here.
Seems like the script can not set correctly the wireguard instance, especially the "Tunnel address".
If a set it manually, information from debug mode, wireguard tunnel work fine, but after "changeserver" it's broken again.

**Comment by AlexBredesen** [comment]
Yeah I'm having the same issue. I did notice some entries in the my VPNS logs. Not 100% sure if it's related.


`wireguard | /usr/local/opnsense/scripts/Wireguard/wg-service-control.php: The command '/sbin/route -q -n add '-4' '10.10.0.1' -iface 'wg3'' returned exit code '1', the output was ''`

**Comment by bedub1** [comment]
> Hi, Same issue here. Seems like the script can not set correctly the wireguard instance, especially the "Tunnel address". If a set it manually, information from debug mode, wireguard tunnel work fine, but after "changeserver" it's broken again.

How did you set it manually?

**Comment by FingerlessGlov3s** [comment]
I've gotten 23.7.6 working on my setup. Please run the below commands to update your installation, you should end up with a working gateway again.

`fetch -o /conf https://raw.githubusercontent.com/FingerlessGlov3s/OPNsensePIAWireguard/main/PIAWireguard.py`
`/conf/PIAWireguard.py changeserver`

**Comment by FreakyBigFoot** [comment]
I just rebooted after doing this and it won't come online. Will the cron job no longer work with this setup?

**Comment by FingerlessGlov3s** [comment]
With the cron configured for every 5 minutes, within 5 minutes of me rebooting OPNsense it had reconfigured the gateway correctly and it's working.

![image](https://github.com/FingerlessGlov3s/OPNsensePIAWireguard/assets/3495647/d8afa1ec-0f70-46a9-bd92-c90e731dd8eb)

**Comment by PatSloan** [comment]
> I've gotten 23.7.6 working on my setup. Please run the below commands to update your installation, you should end up with a working gateway again.
> 
> ```
> fetch -o /conf https://raw.githubusercontent.com/FingerlessGlov3s/OPNsensePIAWireguard/main/PIAWireguard.py
> 
> /conf/PIAWireguard.py changeserver
> ```

working for me.  Thanks.

**Comment by bedub1** [comment]
Can confirm my tunnel is back up and healthy

**Comment by fabricemrchl** [comment]
> I've gotten 23.7.6 working on my setup. Please run the below commands to update your installation, you should end up with a working gateway again.
> 
> ```
> fetch -o /conf https://raw.githubusercontent.com/FingerlessGlov3s/OPNsensePIAWireguard/main/PIAWireguard.py
> 
> /conf/PIAWireguard.py changeserver
> ```

Works fine for me also.
Thank you for your quick fix !

Could you create github realease when you make some change ?
I'm used to subscribe to realease notification so I can easily follow what's new and know when I need to make an upgrade.

**Comment by FingerlessGlov3s** [comment]
I shall create a release :-)
