### ISSUE TITLE
Cannot run simultaneous connections

### ISSUE THREAD

**Issue by Enter-An-Username** [FingerlessGlov3s/OPNsensePIAWireguard#45]
I want to have simultaneous connections to various PIA servers (local server for low ping, international server for privacy, other international servers for Nexflix). I created a new copy of both PIAWireguard.json and PIAWireguard.py with a new name like PIAWireguard2.  Inside PIAWireguard2.json, I changed the "opnsenseWGName" to PIA_2 and chose a different sever, all the rest of the fields the same as described in the tutorial.  Then, inside of PIAWireguard2.py I find/replace all instances of PIAWireguard.json with PIAWireguard2.json.  Finally, I followed the tutorial again by putting a "2" after all things to create and establish a second connection.  All of the scripts run and I get a connection to the second server but...  in the Gateway tab, the second server has a gateway IP, but shows offline with 100% loss of ping.  There must be other hard-coded references to PIAWireguard.py or PIAWireguard.json that I am missing.  Also, I do not understand how to create a second cron job to mind the second connection.  Thanks for your hard work on this project!

**Comment by FingerlessGlov3s** [comment]
Multi copies isn't officially supported. I am thinking about rewriting the script at some point to support this.

Effectively people are making an editted copy the .py file, making a second json config file and then a copy of the actions file, amended to the new name of the py file.

**Comment by MonkeyGoneWIld** [comment]
Did you change the opnsenseWGPort in json file?

https://github.com/FingerlessGlov3s/OPNsensePIAWireguard/issues/42#issuecomment-1749835261

**Comment by bedub1** [comment]
You need to go change your PIA Password, opnsense secrets, DIP tokens.

**Comment by Enter-An-Username** [comment]
Thanks MonkeyGoneWIld.  The reference to #42 was very helpful.  I changed everything as shown in the screen shot but I am still having some trouble.  Do I need to create a new OPNsense user for each instance (IE unique keys)?

**Comment by Enter-An-Username** [comment]
After a reboot it is working great with 3 simultaneous connections so far.  Thanks again.
