### ISSUE TITLE
Tunnels Broken

### ISSUE THREAD

**Issue by socal0001** [FingerlessGlov3s/OPNsensePIAWireguard#46]
Suddenly my tunnel is broken today.  Anybody else?  Mine has been working for years.  I did not change anything. 

When I run ./PIAWireguard.py debug (or debug changeserver) everything works.  

But when I try to put anything through the tunnel it fails.  
pinging the server_ip works
pinging the server_vip fails, no response.
pinging 10.0.0.243 fails, no response.

I turned on logging on my opnsense firewall rules and things are going through the firewall fine.

I tried updating opnsense to the latest, no help.  

Any suggestions?  Thanks for reading.

**Comment by FingerlessGlov3s** [comment]
Make sure your on the latest version of the python script.

**Comment by FingerlessGlov3s** [comment]
If you click watch for releases on this repo, I'm gonna gonna be releases when the script needs updating due to breaking changes in the OPNsense updates.
