### ISSUE TITLE
Opnsense 23.7.8 update to wireguard causing script issues.  Gateway not coming up after boot. no internet.  

### ISSUE THREAD

**Issue by PatSloan** [FingerlessGlov3s/OPNsensePIAWireguard#47]
I updated to 23.7.8 and the script is not working again.  Similar to the issue I reported with the 23.7.7 update.  PIA gateway does not come up.  After 10 minutes or so I tried restarting the wireguard service, and the gateway came up as green.  *BUT* the devices I have running through that gateway do not get any internet access. 

23.7.8 includes wireguard 2.5 update. just FYI. 

I have rolled back to 23.7.7.3 and all is well now.

**Comment by andiweidl** [comment]
Hello all, 

thanks to PatSloan to write this here....
I have the same Problem now

Is it possible, that you update your Scripts in the next Time?

Many Thanks from Austria :-)

**Comment by iShark5060** [comment]
the "script errors" btw are:

`[10-Nov-2023 02:45:02 Europe/Berlin] TypeError: explode(): Argument #2 ($string) must be of type string, array given in /usr/local/opnsense/mvc/app/controllers/OPNsense/Wireguard/Api/ClientController.php:79
Stack trace:
#0 /usr/local/opnsense/mvc/app/controllers/OPNsense/Wireguard/Api/ClientController.php(79): explode(',', Array)
#1 [internal function]: OPNsense\Wireguard\Api\ClientController->setClientAction('45e182d1-f2c3-4...')
#2 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->callActionMethod(Object(OPNsense\Wireguard\Api\ClientController), 'setClientAction', Array)
#3 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->dispatch()
#4 /usr/local/opnsense/www/api.php(24): Phalcon\Mvc\Application->handle('/api/wireguard/...')
#5 {main}`

**Comment by bedub1** [comment]
Gah!  I saw these posts and ignored them, then updated my opnsense.  I should have paid more attention.  I'm broken too.

**Comment by FingerlessGlov3s** [comment]
I've updated the script now to fix the problems with the new update. Sorry for the delay, been little under the weather.

https://github.com/FingerlessGlov3s/OPNsensePIAWireguard/releases/tag/23.7.8-1

**Comment by andiweidl** [comment]
Thanks for the quick update..

I have now installed and the VPN is up and running :-)

Best Regards

**Comment by westy** [comment]
Cheers Glov3s! I'll take a look later.

Hope feel better soon!

**Comment by EeroV** [comment]
that fixed my vpn also. thanks

**Comment by FingerlessGlov3s** [comment]
Issue has been fixed with https://github.com/FingerlessGlov3s/OPNsensePIAWireguard/releases/tag/23.7.8-1
