### ISSUE TITLE
OPNSense 23.7.8_1 has been released - Ensure compatibility

### ISSUE THREAD

**Issue by bedub1** [FingerlessGlov3s/OPNsensePIAWireguard#48]
Hello!

I see OPNSense 23.7.8_1 has been released.  Can you please test it, and ensure FingerlessGlov3s is compatible?  Please?  :)

**Comment by iShark5060** [comment]
haven't rebooted yet, but my tunnels remained up after updating

**Comment by FingerlessGlov3s** [comment]
My testing shows the script works with the hotfix OPNsense released.
