### ISSUE TITLE
problems until I "apply" firewall rules (after reboot)

### ISSUE THREAD

**Issue by freaky-m0** [FingerlessGlov3s/OPNsensePIAWireguard#49]
Since the last two versions of the script I have weird issues. With 23.7.8 and the latest script I get this if I reboot the firewall:

I try to make a nslookup and it doesn't work. Then I change ANY rule to "activate log" (for example, the change doesn't matter) and hit apply. After that everything works as expected.
![grafik](https://github.com/FingerlessGlov3s/OPNsensePIAWireguard/assets/4473764/b3200ae0-75ac-400f-afe2-e2fd960ad7ec)

Any idea what could be wrong on my side? Thanks in advance :)

**Comment by FingerlessGlov3s** [comment]
Very strange, wonder if that's a opnsense bug rather than a script one 🤔. Now I could maybe reload the rules but problem is it may apply pending rules that someone doesn't what to apply yet 🤔

**Comment by freaky-m0** [comment]
Any rule. I can see that OPNsense accepts the packages but then nothing seems to be routed/forwarded.

**Comment by EeroV** [comment]
maybe its nat issue?

**Comment by FingerlessGlov3s** [comment]
Could be NAT.

Maybe if you can try flushing the different parts of PF

https://www.openbsdhandbook.com/pf/cheat_sheet/

**Comment by freaky-m0** [comment]
Flushing (NAT, RULES, QUEUE, ALL) did not change anything. (When I flushed ALL it seems everythin stopped working > then I restartet OPNsense, but maybe that is expected)

I checked the captured packages again. It comes into the LAN IF and does not leave the PIA_GW IF. The input rules on the LAN IF trigger and the package get's accepted by the firewall rule.

**Comment by bedub1** [comment]
Do you have a "kill switch" type of rule in place?  

I've noticed that I can reboot the firewall, 5 minutes later the PIA VPN tunnel comes up.  But the Firewall rule that sends traffic over it, isn't respected.  My traffic still flows directly out the WAN.  I have to bounce a firewall rule to get the traffic to flow over the VPN.

**Comment by freaky-m0** [comment]
Yes I have the "kill switch" rule. (https://docs.opnsense.org/manual/how-tos/wireguard-selective-routing.html#step-11-add-a-kill-switch-optional)

The rule is respected. I can the this in the firewall logs (I have loggging enabled on this rule). But the gateway is ignored. Could you check this on your firewall @bedub1. If then I think we have the same problem.

Maybe there is some problem with the gateway being not avaible when the rule gets "activated" on boot? So it never sets it right until wie refresh/reapply the rules?

**Comment by FingerlessGlov3s** [comment]
Could be when the gateway comes up it's not sending a signal or whatever is needed to the rules to make the gateway option work again 🤔.

They did recently change how wireguard and the gateways UI recently, wonder if some backend changes have changed things...

**Comment by bedub1** [comment]
I added the kill switch rule.  I rebooted.  The VPN comes up.  

The traffic with the kill switch just dies, goes nowhere.  The traffic without the kill switch goes out the WAN.  

I click "enable" and then "disable" on a Firewall Rule, and then click Apply.  Which doesn't actually change anything.  

Now my kill switch traffic flows out the VPN instead of going nowhere, and the non-kill switch traffic flows over the VPN instead of the WAN.

**Comment by bedub1** [comment]
Posted here:  https://forum.opnsense.org/index.php?topic=37076.0

**Comment by freaky-m0** [comment]
![grafik](https://github.com/FingerlessGlov3s/OPNsensePIAWireguard/assets/4473764/13aa5c55-bf6b-47c4-ad6f-673a15cd53b8)
That is not the cause. I will register/post there

**Comment by freaky-m0** [comment]
I updated to 23.7.10 today and it seems to be fixed. Can you confirm this?

Changelog:
o plugins: os-wireguard fix for missing firewall reload
o plugins: os-wireguard-go fix for device registration

**Comment by FingerlessGlov3s** [comment]
I'm running this version myself and so far I've seen no problems. 👍
