### ISSUE TITLE
piaWireGuardChangeServer action doesn't seems to work

### ISSUE THREAD

**Issue by kumy** [FingerlessGlov3s/OPNsensePIAWireguard#5]
From what I've found, the `piaWireGuardChangeServer` as it is written in `actions_piawireguard.conf` doesn't use the `parameters`.

I got success with either of those solution:
- moving the `parameter` to the `command` line
- substitute the `parameter` value by `%s` and specify the `changeserver` action directly in the interface:

![Screenshot from 2021-01-22 18-37-05](https://user-images.githubusercontent.com/176794/105525297-30241480-5ce1-11eb-9c78-40d6fad56cae.png)

The later would permit to reduce the number of actions in that file. I was testing is the syntax `%s %s` would always work, with/without parameter or with 1 or 2 parameters until I exceeded my API limit on PIA side ;), but at first it seemed to works as expected.

The whole file could be trimed to (passing parameter in the UI): (to be verified)
```
[piaWireGuard]
command:/conf/PIAWireguard.py
parameters:%s %s
type:script
message:Running PIA WireGuard script
description:PIA WireGuard
```

However, I'll provide a PR which should be backward compatible. Don't want to introduce breaking changes myself :wink: 

https://docs.opnsense.org/development/backend/configd.html#action-properties

**Comment by FingerlessGlov3s** [comment]
Guessing you've tested this commit?

**Comment by kumy** [comment]
My PIA API limit has been reset I'll revert all my changes to #6 and confirm in a minute.

**Comment by kumy** [comment]
I confirm it works here :

```
root@gw:~ # cat /usr/local/opnsense/service/conf/actions.d/actions_piawireguard.conf
## /usr/local/opnsense/service/conf/actions.d

[piaWireGuard]
command:/conf/PIAWireguard.py debug
parameters:%s
type:script_output
message:Running PIA WireGuard script, checking wireguard connection
description:PIA WireGuard

[piaWireGuardChangeServer]
command:/conf/PIAWireguard.py debug changeserver
parameters:
type:script_output
message:Running PIA WireGuard script, changing server
description:PIA WireGuard change server

root@gw:~ # service configd restart
Stopping configd...done
Starting configd.

root@gw:~ # configctl piawireguard piaWireGuardChangeServer
WGInstanceUUID: xx
WGPeerUUID: xx
WGInstance: xx
WGPeer: xx
Force server change requested
metaServer
[{'ip': '156.146.63.198', 'cn': 'paris403'}]
wgServer
[{'ip': '84.17.60.216', 'cn': 'paris403'}]
Your PIA Token, DO NOT GIVE THIS TO ANYONE
{
    "status": "OK",
    "token": "xxxxxxxxxx"
}

WG Server connection information
{
    "status": "OK",
    "server_key": "xx",
    "server_port": 1337,
    "server_ip": "84.17.60.216",
    "server_vip": "10.8.128.1",
    "peer_ip": "10.8.176.212",
    "peer_pubkey": "xx",
    "dns_servers": [
        "10.0.0.243",
        "10.0.0.242"
    ]
}

Saved wireguard server information to /tmp/wg0_piaserverinfo
Saved server_vip to /tmp/wg0_router

root@gw:~ # netstat -rn4
Routing tables

Internet:
Destination        Gateway            Flags     Netif Expire
0.0.0.0/1          wg0                US          wg0
default            192.168.2.1        UGS         re0
10.8.176.212       link#14            UH          wg0
84.17.60.216       192.168.2.1        UGHS        re0
…
```

**Comment by FingerlessGlov3s** [comment]
Yeah we could combine the two actions, only thing I think would be little annoying is the log message sin the backend logs, wouldn't say the pia server is changing, if we could pass the parameters in to the message, boom go to go and combine the two together, then update the readme with the new cron method :-)

**Comment by FingerlessGlov3s** [comment]
Going to try this, but not sure this message idea works...

```
## /usr/local/opnsense/service/conf/actions.d

[piaWireGuard]
command:/conf/PIAWireguard.py
parameters: %s %s
type:script_output
message:Running PIA WireGuard script %s %s
description:PIA WireGuard
```

**Comment by kumy** [comment]
No idea to bring the parameter back in the log message.

Also what about changing the type to `type:script_output`, I expect it to also log the command output, (with the possibility to add "debug" flag too.)

**Comment by kumy** [comment]
At first try, your idea seems to work

```
[05e4b2a3-7214-462f-a16d-2b438c09b4e2] Running PIA WireGuard script, checking wireguard connection changeserver
```

```
[piaWireGuard]
command:/conf/PIAWireguard.py debug
parameters:%s
type:script_output
message:Running PIA WireGuard script, checking wireguard connection %s
description:PIA WireGuard
```

**Comment by FingerlessGlov3s** [comment]
Some testing later we can indeed get this down to one action :-)

```
## /usr/local/opnsense/service/conf/actions.d

[piaWireGuard]
command:/conf/PIAWireguard.py
parameters: %s %s
type:script_output
message:Running PIA WireGuard script : /conf/PIAWireguard.py %s %s
description:PIA WireGuard
```

```
[5b2d000d-0f2a-4f18-8a47-19a6a1d156aa] Running PIA WireGuard script : /conf/PIAWireguard.py debug
```

```
configctl piawireguard piaWireGuard debug
```

**Comment by FingerlessGlov3s** [comment]
Haha you slightly beat me too it xD

**Comment by FingerlessGlov3s** [comment]
https://github.com/FingerlessGlov3s/OPNsensePIAWireguard/commit/30f0a3b17a2751fb64fb26f9721f3780e3a1c163

Done this commit which should do the trick :-)

**Comment by kumy** [comment]
Looks fine to me :+1: let's close the other PR.
