### ISSUE TITLE
Failed to import config file /conf/PIAWireguard.json ERROR on OPNSense 23.7.11

### ISSUE THREAD

**Issue by LeftyJohnson** [FingerlessGlov3s/OPNsensePIAWireguard#50]
My wireguard setup on OPNSense 23.7.11 stopped working and where I would normally use this excellent script to make it all work again I am now getting an interesting error.

I downloaded the latest example PIAWireguard.json and filled in the variables but I keep getting "ERROR:Failed to import config file /conf/PIAWireguard.json" when I run PIAWireguard.py (also the latest version).

My JSON with key values and logon information removed:
{
    "opnsenseURL": "https://127.0.0.1",
    "opnsenseKey": "<key>",
    "opnsenseSecret": "<key>",
    "piaUsername": "<user>",
    "piaPassword": "<passwd>",
    "tunnelGateway": null,
    "opnsenseWGPrefixName": "pia",
    "instances": {
        "Canadia": {
            "regionId": "ca",
            "dipToken": "",
            "dip": false,
            "portForward": true,
            "opnsenseWGPort": "51815"
        }
        "Atlanta": {
            "regionId": "us_atlanta",
            "dipToken": "",
            "dip": false,
            "portForward": false,
            "opnsenseWGPort": "51814"
        }
    }
}

**Comment by FingerlessGlov3s** [comment]
I see the problem, there's a comma missing on the instances array. See the double asterisk, is where I added the comma.

You can use https://jsonformatter.org/ to check your json formatting, of course remove passwords/secrets before pasting content in there.

```
{
  "opnsenseURL": "https://127.0.0.1",
  "opnsenseKey": "",
  "opnsenseSecret": "",
  "piaUsername": "",
  "piaPassword": "",
  "tunnelGateway": null,
  "opnsenseWGPrefixName": "pia",
  "instances": {
    "Canadia": {
      "regionId": "ca",
      "dipToken": "",
      "dip": false,
      "portForward": true,
      "opnsenseWGPort": "51815"
    }**,**
    "Atlanta": {
      "regionId": "us_atlanta",
      "dipToken": "",
      "dip": false,
      "portForward": false,
      "opnsenseWGPort": "51814"
    }
  }
}
```

**Comment by LeftyJohnson** [comment]
Foiled by formatting again.

Much appreciated
