### ISSUE TITLE
Does this work if you already have a WG instance running?

### ISSUE THREAD

**Issue by rykr** [FingerlessGlov3s/OPNsensePIAWireguard#52]
I already have a WG instance running that my phones connect to to check on security cameras, etc.  Can I use that WG instance for this or do I need this script to setup a second WG instance?

**Comment by FingerlessGlov3s** [comment]
This script will not touch you wireguard instance you have created for your phones, and will run along side. I have other WireGuard tunnels that run beside the one managed by this script.
