### ISSUE TITLE
Change Servers

### ISSUE THREAD

**Issue by bedub1** [FingerlessGlov3s/OPNsensePIAWireguard#53]
The new script creates 2 commands available in Cron:

- PIA WireGuard Change Tunnel's Server
- PIA WireGuard Monitor Tunnels

In the past I was able to add commands into the Parameters field to change the server.  I'd enable the job, then disable the job after the server was changed.  

Is this still possible?  What Parameters should I add to the "Change Tunnel" command?

**Comment by FingerlessGlov3s** [comment]
In the `PIA WireGuard Change Tunnel's Server`, you just need to put the instance name, say `london`. No need to do the `--changeserver`

**Comment by bedub1** [comment]
I had my cron job setup incorrectly, it was scheduled to run 1 minute after midnight, not every minute.  Fixed the schedule, now I can just enable/disable the job to change servers.  Thanks!
