### ISSUE TITLE
Feature request -- local dns option.

### ISSUE THREAD

**Issue by dicepvp** [FingerlessGlov3s/OPNsensePIAWireguard#57]
the ability to have the instance Ip forward to unbound as a dns server. or forward it to another local dns using unbound. the current issue is the WG instance ip will change from time to time meaning that you have to go and change all the configs regarding the dns constantly.

**Comment by dicepvp** [comment]
its also possible in the pia client. i wander if it would be possible to kind of reverse engineer that if it works by sending a sort of request to the pia server like a dip

**Comment by FingerlessGlov3s** [comment]
Can you please explain in more details what you are wanting or currently doing. I'm not 100% sure I understand what your trying to achieve.

**Comment by dicepvp** [comment]
of course i have a local dns so i can block specific domains like ads. Microsoft updates, trackers, malware, porn etc. as far as im aware the dns must be the same as the wg instance tunnel address otherwise it wont pass traffic correctly. the issue is from time to time the wg tunnel address changes which then breaks the config. in order for this to function currently i have adguardhome listening to the wireguard tunnel address i have created a port forward for the dns/tunnel address using port 53.  i then use dhcpv4 to forward the dns/tunnel address on lan for all of my devices. my idea would be a way to update dhcpv4, firewall port forward and unbound/adguardhome with the new tunnel address each time it changes. i may be able to change my configuration. "im fine with using either adguardhome or unboud as they both can do what i want/need".

**Comment by dicepvp** [comment]
how would i tell the difference between the two?

**Comment by FingerlessGlov3s** [comment]
Does it need to be recursive or would using PIA or another DNS provider be ok? As it would really simplify the configuration to make this work without any intervention 😊

**Comment by dicepvp** [comment]
i believe it does need to be recursive for adguardhome to fully function sadly.

**Comment by FingerlessGlov3s** [comment]
Looks like you can set upstream DNS servers. What we could do is use quad9 or someone else, then use static routes on OPNsense to ensure all traffic going to the quad9 IPs use the PIA tunnel. Then issue you have would disappear 😊

![image](https://github.com/FingerlessGlov3s/OPNsensePIAWireguard/assets/3495647/646d8c8f-8a66-4fa8-a5bc-6427a0338295)

**Comment by dicepvp** [comment]
thanks i will give it a try. what about if i need to use a specific upstream?

**Comment by FingerlessGlov3s** [comment]
Since you already have the PIA gateway configured, you can go straight in to `System: Routes: Configuration` and create a route for each upstream DNS provider IPs

Example
![image](https://github.com/FingerlessGlov3s/OPNsensePIAWireguard/assets/3495647/9ba4ecac-c6e5-4b1c-a593-edd8bf9254fa)

**Comment by dicepvp** [comment]
alright thanks for your help

**Comment by FingerlessGlov3s** [comment]
No problem let me know how it goes 😊.

If you use quad9 you can use https://on.quad9.net/ to test if it's using quad9, then you can use the firewall logs to see if the traffic to quad9 left the right interface 😊

**Comment by bedub1** [comment]
You need to be really careful about this.  

If you reboot your firewall, your VPN tunnel will be down.
If you have your routes configured to send all DNS traffic over the VPN
Then when the system tries to connect the VPN, it'll send a DNS query for the PIA endpoint....over a tunnel that doesn't exist.
You'll never be able to resolve the PIA DNS entry, thus never connect the VPN tunnel.  
You'll end up in a circular dependency situation.
