### ISSUE TITLE
NameError: name 'e' is not defined

### ISSUE THREAD

**Issue by ehbstudentadam** [FingerlessGlov3s/OPNsensePIAWireguard#58]
<img width="962" alt="image" src="https://github.com/FingerlessGlov3s/OPNsensePIAWireguard/assets/92335422/d28128fa-279e-4f3d-9693-b8bd47aa833c">

I am having following error message when running the script.

**Comment by EeroV** [comment]
that is error in config file? probably syntax error

**Comment by ehbstudentadam** [comment]
Seems the error is thrown for instance Belgium. Tried changing the region to following without success.

<img width="1012" alt="image" src="https://github.com/FingerlessGlov3s/OPNsensePIAWireguard/assets/92335422/0e7ce0ca-3bdf-497f-9709-804bbfc09ca3">

**Comment by FingerlessGlov3s** [comment]
What version of opnsense are you running?

**Comment by ehbstudentadam** [comment]
> What version of opnsense are you running?

OPNsense 24.1.1-amd64
FreeBSD 13.2-RELEASE-p9
OpenSSL 3.0.13

**Comment by FingerlessGlov3s** [comment]
> > What version of opnsense are you running?
> 
> OPNsense 24.1.1-amd64
> FreeBSD 13.2-RELEASE-p9
> OpenSSL 3.0.13

Interesting, it's failing to create the peer for the second instance.

Can you also set the regionid of the Belgium one to nl as well I want to see if it's a region issue or not first.

**Comment by ehbstudentadam** [comment]
> > > What version of opnsense are you running?
> > 
> > 
> > OPNsense 24.1.1-amd64
> > FreeBSD 13.2-RELEASE-p9
> > OpenSSL 3.0.13
> 
> Interesting, it's failing to create the peer for the second instance.
> 
> Can you also set the regionid of the Belgium one to nl as well I want to see if it's a region issue or not first.

Same error is thrown

<img width="1115" alt="image" src="https://github.com/FingerlessGlov3s/OPNsensePIAWireguard/assets/92335422/fdb4bba1-9dd2-45b6-9d92-f0771d830c39">

**Comment by ehbstudentadam** [comment]
<img width="1071" alt="image" src="https://github.com/FingerlessGlov3s/OPNsensePIAWireguard/assets/92335422/a9e1f4b3-61f2-4e5c-93ac-178cadefa7cb">

**Comment by FingerlessGlov3s** [comment]
Very strange, sounds like it failed to create the keypair. Not sure why your getting various different errors 😅, wonder if something changed in OPNsense 24.1.1

**Comment by FingerlessGlov3s** [comment]
Ok I've fixed a few bugs now.

If you delete both wg instances and both peers, they'll now get created correctly first try now. Confirmed working on my test OPNsense 24.1.1

**Comment by FingerlessGlov3s** [comment]
Bug was fixed.
