### ISSUE TITLE
Update readme: no System: Gateways: Single option in OPNSense 24.1.1

### ISSUE THREAD

**Issue by ehbstudentadam** [FingerlessGlov3s/OPNsensePIAWireguard#59]
<img width="1070" alt="image" src="https://github.com/FingerlessGlov3s/OPNsensePIAWireguard/assets/92335422/dc986c00-5810-4314-afe5-e66840242aa9">

**Comment by FingerlessGlov3s** [comment]
They moved it to the bottom right now, see the plus button

**Comment by FingerlessGlov3s** [comment]
Fixed in https://github.com/FingerlessGlov3s/OPNsensePIAWireguard/commit/0922b2e9d054c2cf9ddd6053e6f303870bf02736
