### ISSUE TITLE
OPNSense v24.1.2

### ISSUE THREAD

**Issue by bedub1** [FingerlessGlov3s/OPNsensePIAWireguard#60]
Has anybody upgraded to v24.1.2 yet?  Does the script still work?  I see the following in the changelog:

- wireguard: key constraints should only apply on peers and not instances
- wireguard: peer uniqueness should depend on pubkey + endpoint
- wireguard: skip attached instance address routes
- wireguard: remove duplicate ID columns

**Comment by iShark5060** [comment]
![image](https://github.com/FingerlessGlov3s/OPNsensePIAWireguard/assets/15010489/42815efe-5588-4636-8836-08bb36522473)

![image](https://github.com/FingerlessGlov3s/OPNsensePIAWireguard/assets/15010489/812d0a77-72ef-4201-a46d-42f11551be91)

![image](https://github.com/FingerlessGlov3s/OPNsensePIAWireguard/assets/15010489/be5ba136-fae9-40ce-aca3-587f896e9b95)

![image](https://github.com/FingerlessGlov3s/OPNsensePIAWireguard/assets/15010489/68bbcd86-cd8a-4b35-83a3-b7a51c46ebc0)

works for me ... even though I get some errors in the Log:

![image](https://github.com/FingerlessGlov3s/OPNsensePIAWireguard/assets/15010489/54f5cb22-2bbf-40be-8208-e37a0a8326bf)

**Comment by FingerlessGlov3s** [comment]
Those logs are to be expected, I didn't see those changes as they would cause issues, but glad to see it's working nicely.

**Comment by bedub1** [comment]
I upgraded my instance, and it appears to be working properly as well.
