### ISSUE TITLE
multiple tunnels

### ISSUE THREAD

**Issue by dicepvp** [FingerlessGlov3s/OPNsensePIAWireguard#64]
whats currently the correct way to do multiple tunnels? i would like to have one tunnel that handles most of my devices and a second tunnel with port forwarding for just my server. im a tiny bit confused on how im supposed to do this, this was my guess. or should i follow the ticket from 2021?

        "chicago": {
            "regionId": "us_chicago",
            "dipToken": "",
            "dip": false,
            "portForward": false,
            "opnsenseWGPort": "51815",	
        "ontario": {
            "regionId": "ca_ontario",
            "dipToken": "",
            "dip": true,
            "portForward": true,
            "opnsenseWGPort": "51816"
	    }
        }		
    }
}

**Comment by iShark5060** [comment]
example config from the readme, filled in with your info above:

`{
    "opnsenseURL": "https://127.0.0.1:443",
    "opnsenseKey": "/FQDXExojUWWuBdnPEPCUt98vnrQOdLxFqypTIEhE41304uYgA68ZJw7fveXBpXkMHqiAdx04cRAlLwh",
    "opnsenseSecret": "p+Gi4uE1xypuGIptbhrDylGKcNd9vaRpQ298eH0k6SFRQ6Crw4fLk0cIA0eSuKvWEN0hKx8JaIGUtNPq",
    "piaUsername": "p1234567",
    "piaPassword": "EncryptAllTheThings",
    "tunnelGateway": null,
    "opnsenseWGPrefixName": "pia",
    "instances": {
        "chicago": {
            "regionId": "us_chicago",
            "dipToken": "",
            "dip": false,
            "portForward": false,
            "opnsenseWGPort": "51815"
        },
	"ontario": {
            "regionId": "ca_ontario",
            "dipToken": "",
            "dip": false,
            "portForward": true,
            "opnsenseWGPort": "51816"
        }
    }
}`

**Comment by FingerlessGlov3s** [comment]
Closing as this seems stale, if not please reopen
