### ISSUE TITLE
Failed to list OPNSense WG Instances

### ISSUE THREAD

**Issue by kristofferls** [FingerlessGlov3s/OPNsensePIAWireguard#65]
Hi! Thank you for all your hard work! 

Im stuck at the point in the tutorial where Im to execute the script to set up the WG instance etc. I get this HTTP error: 

DEBUG:JSON validation successful.
DEBUG:Getting OPNsense WireGuard Instances
DEBUG:Starting new HTTPS connection (1): 127.0.0.1:443
DEBUG:https://127.0.0.1:443 "GET /api/wireguard/server/searchServer/ HTTP/1.1" 502 7775
**_ERROR:Failed to list OPNsense WG Instances - Error message: GET Request: Failed returned non 200 status code -_** <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
    <title>Request Denied</title>
    <meta name="generator" content="OPNsense" />
    <meta name="language" content="en-US" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <style>
        body {
            background-color: black;
            max-width: 1000px;
            margin: auto;
            padding-top: 20px;
        }
        h1, p, span, a, .footertext {
            text-align: center;
            color: white;
            vertical-align: baseline;
        }
        @media screen and (min-width: 700px) {
            .logo {
                float: right;
            }
            .footertext {
                text-align: left;
                float: left;
                position: absolute;
                bottom: 0px;
            }
            footer {
                height: 55px;
                position: relative;
            }
            img {
                float: right;
            }
        }
        @media screen and (max-width: 699px) {
            .footertext {
                margin-bottom: 10px;
            }
            footer a {
                display: block;
                text-align: center;
            }
        }
    </style>
</head>
<body>
    <h1>Server Error</h1>
    <p>Sorry, but something went wrong on our side.</p>
    <p>There is nothing you can do except waiting until we fix the issue.</p>
    <hr />
    <footer>
          <div class="footertext">Web Application Protection by OPNsense</div>

I´ve tripple checked the Effective Privileges, and it all seems right.. Im running version 24.1.5_3 of OPNsense. 

Any hints / tips to what might be causing this error?

**Comment by FingerlessGlov3s** [comment]
To check it's not permissions given the user on opnsense full administrator permissions. Or download the API keys for the root account.

**Comment by FingerlessGlov3s** [comment]
Just found some time to test the script on my test OPNsense running 24.1.5_3, the script was able to create 2 new tunnels, from having nothing setup in OPNsense.

So it must be permissions or maybe the ``opnsenseURL` in the config file.

**Comment by kristofferls** [comment]
Sorry for my late reply! I've just installed a new OpnSense instance on Proxmox, and went trough the process again. Worked flawlessly! Thank you for all your hard work!!

**Comment by MrDuckenstein** [comment]
> Sorry for my late reply! I've just installed a new OpnSense instance on Proxmox, and went trough the process again. Worked flawlessly! Thank you for all your hard work!!

Damn, I am having the same issue and was watching this hoping for a fix!

Everything worked for me when setting my VPN's up a few weeks ago, after a power outage they all became defunct, after tweaking some things that didn't work I decided to start fresh and removed all my VPN's and started the guide from the top, however I am getting the same issue you were.

"root@OPNsense:~ # /conf/PIAWireguard.py --debug
DEBUG:JSON validation successful.
DEBUG:Getting OPNsense WireGuard Instances
DEBUG:Starting new HTTPS connection (1): 127.0.0.1:443
DEBUG:https://127.0.0.1:443 "GET /api/wireguard/server/searchServer/ HTTP/1.1" 500 None
ERROR:Failed to list OPNsense WG Instances - Error message: GET Request: Failed returned non 200 status code - {"errorMessage":"Unexpected error, check log for details"}"

The permissions for the user has not changed (I did try granting Admin permissions, no change), neither has the opnsenseURL.

I am so stuck... Any ideas how I can get it working without reinstalling Opnsense?

**Comment by FingerlessGlov3s** [comment]
Have you checked the logs of opnsense itself to see if it's reported what the error is, it says to check that in the returned response.

Also the webui is running on port 443 right? You haven't moved it to another port so say HAProxy can use port 443?

**Comment by FingerlessGlov3s** [comment]
Stale
