### ISSUE TITLE
Step 15 - Setup CRON job

### ISSUE THREAD

**Issue by sedgbeer** [FingerlessGlov3s/OPNsensePIAWireguard#67]
OPNSense 24.1.8
No option for setting up CRON job as described in step 15.
![image](https://github.com/FingerlessGlov3s/OPNsensePIAWireguard/assets/155904827/5d864415-3a06-46ec-ae0d-b7a06ccc5fd8)

**Comment by FingerlessGlov3s** [comment]
Does `/usr/local/opnsense/service/conf/actions.d/actions_piawireguard.conf`

```
root@OPNsense:/usr/local/opnsense/service/conf/actions.d # ls -lsa /usr/local/opnsense/service/conf/actions.d/actions_piawireguard.conf
4 -rw-r--r--  1 root  wheel  482 Jan 18 19:06 /usr/local/opnsense/service/conf/actions.d/actions_piawireguard.conf
```

If it doesn't exist run the below, and check it exists.
```
fetch -o /usr/local/opnsense/service/conf/actions.d https://raw.githubusercontent.com/FingerlessGlov3s/OPNsensePIAWireguard/main/actions_piawireguard.conf
```

Then restart the configd service
```
service configd restart
``` 

Give those steps a try and see how it goes.

**Comment by sedgbeer** [comment]
Ta! That got them sorted. 
I'm sure I didnt miss a setup when setting up.
Thanks for the assist!
