### ISSUE TITLE
Unable to --debug or --changeserver

### ISSUE THREAD

**Issue by Des-m0nd** [FingerlessGlov3s/OPNsensePIAWireguard#68]
`requests.exceptions.ConnectionError: HTTPSConnectionPool(host='serverlist.piaservers.net', port=443): Max retries exceeded with url: /vpninfo/servers/v6 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x84cd76640>: Failed to establish a new connection: [Errno 51] Network is unreachable'))`

Running /conf/PIAWireguard.py --debug or  --debug --changeserver will result in the error above

**Comment by FingerlessGlov3s** [comment]
Hi,

Able you able to curl the v6 servers url in the OPNsense console, if it doesn't work sounds like your unable to route to PIA for some reason, this isn't a fault of the script.

```
# curl https://serverlist.piaservers.net/vpninfo/servers/v6
```

**Comment by Des-m0nd** [comment]
curl: (7) Failed to connect to serverlist.piaservers.net port 443 after 34 ms: Couldn't connect to server

right... seems like I can't curl to that server, are there any alternative servers that I can use? Also, were you able to curl to https://serverlist.piaservers.net/vpninfo/servers/v6?

**Comment by FingerlessGlov3s** [comment]
That's the master server list, so you need to be able to get too that URL to retrieve the list of servers for all of the PIA regions.

I can indeed curl it.

**Comment by Des-m0nd** [comment]
Dang it, I can access https://serverlist.piaservers.net/vpninfo/servers/v6 via browser but not curl it, both devices are on the same network

**Comment by FingerlessGlov3s** [comment]
You'll need to workout what you've done that's stopped you being able to curl that URL on OPNsense.

**Comment by Des-m0nd** [comment]
I managed to run  --debug --changeserver vn the first time to add in another region, 
```
"vn": {
            "regionId": "vietnam",
            "dipToken": "",
            "dip": false,
            "portForward": false,
            "opnsenseWGPort": "51816"
        },
```

But when I tried to change the regionId to "kr_south_korea-pf", and run  --debug --changeserver vn again this happened. Do you know what could have happened?

**Comment by FingerlessGlov3s** [comment]
What happened, did you forget to copy in the output?  All I can see if the instance config json.

Or do you mean it broke after changing the config?

Also version of OPNsense are you running?

**Comment by Des-m0nd** [comment]
I managed to resolve this by restarting the service routing on my opnsense, does it add any routing when running the script?

**Comment by FingerlessGlov3s** [comment]
Only 1 small route, nothing that changes the default route.

**Comment by Des-m0nd** [comment]
Seems like it is working, may I ask if I want to change the region from vn to hk, what is the proper steps to do it? Do I just change the regionId to "hk" in the json and run the --changeserver vn flag?

**Comment by FingerlessGlov3s** [comment]
the instance name is what you use in the command, if you want to change the regionid inside the instance, then you just return the `--changeserver instancename`

Of course you ideally want to keep the instance name meaningful.

**Comment by Des-m0nd** [comment]
If I want to rename the instancename in the json, I have to delete the previous instances and peer in the Wireguard?

**Comment by FingerlessGlov3s** [comment]
Yeah you'll want to cleanup the changes the script made to opnsense, go in and delete the gateway, wireguard bits, aliases etc

**Comment by Des-m0nd** [comment]
Okay, thank you very much for your assistance!
