### ISSUE TITLE
Issue using script after upgrade to 24.7

### ISSUE THREAD

**Issue by wakeboard143** [FingerlessGlov3s/OPNsensePIAWireguard#69]
Hello! 

Script was working perfectly before the upgrade, but now failing when trying to set port-forwarding. It appears to establish the connection and bring up the tunnel just fine. Here is the relevant debug logging:

root@firewall:/conf # /conf/PIAWireguard.py --debug --changeserver all
DEBUG:JSON validation successful.
DEBUG:Getting OPNsense WireGuard Instances
DEBUG:Starting new HTTPS connection (1): <<firewallFQDN>>:8443
DEBUG:https://<<firewallFQDN>>:8443 "GET /api/wireguard/server/searchServer/ HTTP/1.1" 200 None
DEBUG:Creating/Populating Wireguard Instances array
DEBUG:Setting up python script for instance vancouver
DEBUG:Looking for server instance pia-vancouver in gathered opnsense instances
DEBUG:Getting WireGuard instance for vancouver
DEBUG:https://<<firewallFQDN>>:8443 "GET /api/wireguard/server/getServer/ HTTP/1.1" 200 None
DEBUG:Getting peer details (PIA's Server)
DEBUG:https://<<firewallFQDN>>:8443 "GET /api/wireguard/client/getClient/ HTTP/1.1" 200 None
DEBUG:Finished getting vancouver tunnel instance information from OPNsense
DEBUG:Checking handshakes
DEBUG:https://<<firewallFQDN>>:8443 "GET /api/wireguard/service/show/ HTTP/1.1" 200 None
DEBUG:vancouver tunnel forced change server requested
DEBUG:Starting new HTTPS connection (1): serverlist.piaservers.net:443
DEBUG:https://serverlist.piaservers.net:443 "GET /vpninfo/servers/v6 HTTP/1.1" 200 None
DEBUG:Changing server for tunnel instance vancouver
DEBUG:metaServer: vancouver431 181.41.202.5
DEBUG:wgServer: vancouver431 181.41.202.101
DEBUG:Starting new HTTPS connection (1): vancouver431:443
DEBUG:https://vancouver431:443 "GET /authv3/generateToken HTTP/1.1" 200 164
DEBUG:Your PIA Token (Meta), DO NOT GIVE THIS TO ANYONE: <<REDACTED>>
DEBUG:Starting new HTTPS connection (1): vancouver431:1337
DEBUG:https://vancouver431:1337 "GET /addKey?<<REDACTED>> HTTP/1.1" 200 348
DEBUG:Saved wireguard server information to /tmp/wg0_piaserverinfo
DEBUG:Updating server instance: pia-vancouver
DEBUG:https://<<firewallFQDN>>:8443 "GET /api/wireguard/server/getServer/ HTTP/1.1" 200 None
DEBUG:https://<<firewallFQDN>>:8443 "POST /api/wireguard/server/setServer/ HTTP/1.1" 200 None
DEBUG:Updated server instance
DEBUG:Updating peer: pia-vancouver-server
DEBUG:https://<<firewallFQDN>>:8443 "GET /api/wireguard/client/getClient/ HTTP/1.1" 200 None
DEBUG:https://<<firewallFQDN>>:8443 "POST /api/wireguard/client/setClient/ HTTP/1.1" 200 None
DEBUG:Updated peer
DEBUG:Checking WireGuard service enabled
DEBUG:https://<<firewallFQDN>>:8443 "GET /api/wireguard/general/get HTTP/1.1" 200 None
DEBUG:https://<<firewallFQDN>>:8443 "POST /api/wireguard/service/reconfigure HTTP/1.1" 200 None
DEBUG:Saved server_vip to /tmp/wg0_router
DEBUG:Tunnel instance vancouver has been changed to a new PIA server
DEBUG:Waiting 10 seconds for new WireGuard server(s) to apply before applying port forwarding
DEBUG:Processing port forward for tunnel instance vancouver
DEBUG:Starting new HTTPS connection (1): vancouver431:443
DEBUG:https://vancouver431:443 "GET /authv3/generateToken HTTP/1.1" 200 164
DEBUG:Starting new HTTPS connection (1): vancouver431:19999
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1060, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x27db6d6a0c10>, 'Connection to vancouver431 timed out. (connect timeout=10)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 801, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 594, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='vancouver431', port=19999): Max retries exceeded with url: /getSignature?token=<<REDACTED>> (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x27db6d6a0c10>, 'Connection to vancouver431 timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/conf/PIAWireguard.py", line 871, in <module>
    request = GetRequest(getSignatureRequestsSession, f"https://{wireguardServerInfo['server_name']}:19999/getSignature", createObject)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/conf/PIAWireguard.py", line 116, in GetRequest
    r = session.get(url, params=params, timeout=10)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 688, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='vancouver431', port=19999): Max retries exceeded with url: /getSignature?token=<<REDACTED>> (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x27db6d6a0c10>, 'Connection to vancouver431 timed out. (connect timeout=10)'))

**Comment by FingerlessGlov3s** [comment]
I've just done some testing on the latest version of 24.1 and 24.7. In my environment both work as expected.

Please sure your version of the script is fully up to date 😊

Versions Tested.
24.1.10_8
24.7_9

**Comment by wakeboard143** [comment]
Ah. Must have been fixed in one of the subsequent hotfixes. I was still on 24.7; upgrading to 24.7_9 resolved it. Thanks for the work!
