### ISSUE TITLE
SSL problem

### ISSUE THREAD

**Issue by boistordu** [FingerlessGlov3s/OPNsensePIAWireguard#7]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 488, in wrap_socket
    cnx.do_handshake()
  File "/usr/local/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1828, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1566, in _raise_ssl_error
    _raise_current_error()
  File "/usr/local/lib/python3.7/site-packages/OpenSSL/_util.py", line 57, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]
```

I have a current openvpn pia connection too working correctly and the certificate seems to be the same so I don't know which certificate he's having problem to verify.

**Comment by boistordu** [comment]
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 371, in connect
    ssl_context=context,
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 386, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 494, in wrap_socket
    raise ssl.SSLError("bad handshake: %r" % e)
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='serverlist.piaservers.net', port=443): Max retries exceeded with url: /vpninfo/servers/v4 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./PIAWireguard.py", line 337, in <module>
    r = requests.get(piaServerList)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='serverlist.piaservers.net', port=443): Max retries exceeded with url: /vpninfo/servers/v4 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
```

that's because your page serverlist is 404

**Comment by FingerlessGlov3s** [comment]
Is your OPNsense up to date, might be the CA that PIA is using for that URL isn't in the cert store.

The server list url in the script is correct and I've just tested "https://serverlist.piaservers.net/vpninfo/servers/v4", loads fine and is signed by R3 Lets Encrypt

**Comment by boistordu** [comment]
Yeah it's up to date to 21.1.3
And as I said an OpenVPN connection is already active to PIA. So I have been obligated to incorporate the certificate auth of PIA in the very store.

That s why I don't really understand why this error. And as I said also I ve compared the cert of your GitHub and the very I have in the instance and it's the same.

Any other ideas ?

**Comment by FingerlessGlov3s** [comment]
"certificate auth of PIA in the very store" What do you mean, PIA doesn't use certificate authentication.

The HTTPS URL your having problems with isn't signed by PIA's internal CA, its signed by Lets Encrypt so that's not the issue.
Can you try curling the URL, see if that also has cert issues
`curl https://serverlist.piaservers.net/vpninfo/servers/v4`

**Comment by boistordu** [comment]
very = cert obviously. Sorry I was on my phone at the time to write that message

an openvpn client wouldn't work without having the good certificate authority in the cert store, are we agreing on that? Because that's what I was telling you actually and that's what I thought the first part of the error message was about. 

curl failed indeed:

```
curl: (60) SSL certificate problem: self signed certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by FingerlessGlov3s** [comment]
Oh you also meant authority, usually authentication is short for auth. So it threw me off. Anyway that stuff you've done to get OpenVPN working with PIA isn't relevant for your issue at the moment.

Ok so you shouldn't be getting "SSL certificate problem: self signed certificate" when you try curl that, is something man in middling your traffic to that URL, the web server your getting the list from should be signed by Lets Encrypted as I stated in my last reply.

If you run the following command this time with -v so its verbose. `curl -v https://serverlist.piaservers.net/vpninfo/servers/v4`
What you should then see is the basic certificate information of the web server which should be the same as below verbose output from my opnsense.
I wonder what certificate your getting back, because clearly its not the right certificate.
```
* Server certificate:
*  subject: CN=serverlist.piaservers.net
*  start date: Dec 30 12:56:51 2020 GMT
*  expire date: Mar 30 12:56:51 2021 GMT
*  subjectAltName: host "serverlist.piaservers.net" matched cert's "serverlist.piaservers.net"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
```

Can you also `ping serverlist.piaservers.net`
So we can see what IP address resolves for you.

**Comment by FingerlessGlov3s** [comment]
issue has gone stale, closing issue. Will re-open if response comes back.

**Comment by boistordu** [comment]
Sorry for the delay I just had the time to actually act upon it. 
So indeed you were right, there was a problem in my routing system, I forgot about a specific rule I had created in the beginning which was filtering this and put the firewall as the destination.
So my bad really.
Thanks again for pointing that to me.

**Comment by FingerlessGlov3s** [comment]
No problem, I'm guessing you've got it up and running now?
