### ISSUE TITLE
How can I remove it?

### ISSUE THREAD

**Issue by rykr** [FingerlessGlov3s/OPNsensePIAWireguard#71]
I'm no longer using it and I want to remove it. And I've tried but I'm still getting errors in the log from part of it trying to run

**Comment by FingerlessGlov3s** [comment]
delete the cron entry and then delete the wireguard instance and peer, then anything that hangs off that like the interface etc.

**Comment by rykr** [comment]
I was trying to do that.  but WireguardAPI user appears to not have a crontab and root crontab appears to have nothing related to PIAWireguard

**Comment by FingerlessGlov3s** [comment]
You need to look at cron within the webui 😊

https://docs.opnsense.org/manual/settingsmenu.html#cron

**Comment by rykr** [comment]
Thank.  Didn't even know that was there
